#!/usr/bin/env python3
"""Run #21 stage 3: write reports/2026-08-17.json from /tmp/run21w/derived.json."""
import json
from datetime import datetime, timezone

REPO="/Users/ls/Documents/MultiversX/projects/onchain-quant-agent"
O=json.load(open("/tmp/run21w/derived.json"))
D=json.load(open(f"{REPO}/data/collected/2026-08-17.json"))
prev=json.load(open(f"{REPO}/data/previous.json"))
status=json.load(open("/tmp/run21w/status.json"))

M=O["macro"]; otc=O["otc"]; wave=otc["wave"]; bid=O["bid"]; ex=O["exch"]; cust=O["custody"]
sk=O["staking"]; rw=O["reward"]; tk=O["tokens"]; xx=O["xexchange"]; df=O["defi"]
wi=O["whale_i"]; z=O["z"]
econ=D["economics"]; st=D["stats"]; pecon=prev["economics"]; pact=prev["activity"]
price=M["price"]; pc=M["price_chg"]; staked=M["staked"]
FEE=sk["fee_events"]; F1=FEE[0] if FEE else None; F2=FEE[1] if len(FEE)>1 else None
UNW=sk["unwind"]
hn=otc["net_by_venue"]

def f(x,d=0): return f"{x:,.{d}f}"

# ------------------------------------------------------------------ anomalies
anomalies=[
 {"metric":"otc_wave_window_net_one_way_egld","current_value":round(wave["net_one_way"]),
  "previous_value":round(wave["sum_of_weekly_nets"]),"method":"rule_based","severity":"high",
  "description":f"WAVE #2 DID NOT ESCALATE - AND MEASURING IT PROPERLY REQUIRES NETTING THE WHOLE WAVE, NOT EACH WEEK. Run #20 pre-registered the escalation test: net one-way above ~300,000 on a UPbit tranche above ~350,000 would mean wave #2 matched or exceeded the re-netted run #17 peak. NEITHER fired. UPbit's feed COLLAPSED {100*(otc['upbit_feed']-otc['prev_upbit_feed'])/otc['prev_upbit_feed']:+.0f}% to {f(otc['upbit_feed'])} EGLD (from {f(otc['prev_upbit_feed'])} last week), and the desks sent {f(otc['upbit_return'])} EGLD BACK to UPbit - inventory returning to its source. The weekly figure reads {f(otc['net_one_way'])} net one-way on {f(otc['gross_out'])} gross, but that framing is now demonstrably wrong: netting the WHOLE two-week wave window (Aug 3-17) gives {f(wave['gross_out'])} gross, {wave['circ_pct']:.0f}% circular and {f(wave['net_one_way'])} genuinely one-way - {f(wave['weekly_frame_overstatement'])} EGLD ({wave['overstatement_pct']:.0f}%) LESS than the sum of the two weekly nets ({f(wave['sum_of_weekly_nets'])}). Over the wave window UPbit is a net SOURCE of {f(abs(wave['net_by_venue'].get('UPbit',0)))} while the weekly frame showed it as a -319,000 source then a +116,000 receiver. Terminals over the wave: Binance.com {wave['net_by_venue'].get('Binance.com',0):+,.0f}, Bybit {wave['net_by_venue'].get('Bybit',0):+,.0f}, Gate.io {wave['net_by_venue'].get('Gate.io',0):+,.0f}. Wave #2 therefore delivered about {100*wave['net_one_way']/otc['peak']['net']:.0f}% of the re-netted run #17 peak ({f(otc['peak']['net'])} in a single week) and has stopped feeding."},
 {"metric":"otc_net_one_way_series_backfilled","current_value":round(otc["run16"]["net"]),
  "previous_value":round(otc["run16"]["gross"]),"method":"rule_based","severity":"medium",
  "description":f"THE NET ONE-WAY SERIES NOW HAS FIVE MEASURED ANCHORS (closes run #20 recommendation #7). The two windows whose interpretation drove the most narrative were re-netted this run: run #16 (Jul 6-13) {f(otc['run16']['gross'])} gross is {otc['run16']['circ_pct']:.0f}% circular = {f(otc['run16']['net'])} one-way, and run #18 (Jul 20-27) {f(otc['run18']['gross'])} gross is {otc['run18']['circ_pct']:.0f}% circular = {f(otc['run18']['net'])} one-way. Full measured series: run #16 {f(otc['run16']['net'])} / run #17 {f(otc['peak']['net'])} / run #18 {f(otc['run18']['net'])} / run #19 61,435 / run #20 {f(otc['prev_net'])} / run #21 {f(otc['net_one_way'])}. Circularity across the five backward windows is {otc['run16']['circ_pct']:.0f}%, {otc['peak']['circ_pct']:.0f}%, {otc['run18']['circ_pct']:.0f}%, 80% and {otc['circ_series_pct']['run20']:.0f}% - tight enough to confirm run #20's constant-circularity finding. This week's {otc['circ_pct']:.0f}% is the sole outlier, and the wave-window netting explains exactly why: the return leg landed in a different week from the feed."},
 {"metric":"direct_node_unwind_resolved_as_artifact","current_value":round(sk["corrected_direct"]),
  "previous_value":round(sk["raw_direct_residual"]),"method":"rule_based","severity":"high",
  "description":f"THE THREE-WEEK 'DIRECT-NODE UNWIND' - carried for three runs as the largest unexplained structural flow tracked - IS A MEASUREMENT ARTIFACT. Run #20 recommendation #2 asked which node operators were unstaking. The answer is: probably none. The residual method (economics.staked minus the sum of provider locked) also moves when a DELEGATOR unDelegates, because the EGLD leaves provider 'locked' immediately but stays inside the staking module for the 7-10 epoch unbonding period. This week the residual flipped to {sk['raw_direct_residual']:+,.0f} - and a single wallet ({UNW['address'][:18]}...) accounts for {f(UNW['total'])} of it: an unDelegate of {f(UNW['legs'][0]['amount'])} from p2p_org_ on 2026-08-15 and {f(UNW['legs'][1]['amount'])} from a second provider on 2026-08-14, both currently unbonding ({UNW['legs'][1]['days_to_unbond']:.1f} and {UNW['legs'][0]['days_to_unbond']:.1f} days remaining, read from /accounts/{{addr}}/delegation). Both were ZERO-VALUE transactions carrying the amount in the data field - the run #19 rule. Netting the in-flight unbonding out, direct-node stake actually GREW {sk['corrected_direct']:+,.0f} this week. The runs #18-#20 readings, which showed the residual FALLING while delegation rose, are equally consistent with earlier unbondings COMPLETING (total staked falls, provider locked already reduced) rather than with node operators exiting. The unwind narrative is withdrawn."},
 {"metric":"delegation_service_fee_to_100pct","current_value":100,"previous_value":F1["fee_from_pct"] if F1 else None,
  "method":"rule_based","severity":"high",
  "description":(f"BOTH HIGH-FEE INCUMBENTS SET THEIR SERVICE FEE TO 100%, ZEROING DELEGATOR APR - AND THIS CORRECTS RUN #20's HEADLINE. Run #20 reported egldstakingprovider cutting 24% -> 15% as 'the first competitive fee repricing in twenty runs'. One week later the same provider moved 15% -> 100% (APR 7.82% -> 0), and procryptostaking - the incumbent run #19 named as the one that had NOT cut - went 20% -> 100% (APR 7.37% -> 0). Verified against three independent endpoints (/providers, /providers?identity=, /providers/{{address}}); the owners are DIFFERENT wallets, so this is two unrelated operators making the same move in the same week, not one entity. Both still run 50 nodes. Both kept bleeding: egldstakingprovider {F1['locked_wow_egld']:+,.0f} EGLD and {F1['users_wow']:+d} delegators, procryptostaking {F2['locked_wow_egld']:+,.0f} EGLD and {F2['users_wow']:+d} delegators. A 100% fee is not competition, it is either a wind-down or a deliberate push to force delegators out - and the run #20 'competitive repricing' reading is therefore withdrawn. Note what the delegator response says: {F1['locked_wow_egld']/1:+,.0f} EGLD left egldstakingprovider (-26% of its book) but only {abs(F1['users_wow'])} of {F1['users']+abs(F1['users_wow'])} users - a few large holders moved, the retail base did not, which is participation inertia showing up in the one place where the incentive to move is now absolute."
   ) if F1 and F2 else "No service-fee changes this week."},
 {"metric":"identifiable_bid_absorbed_egld_7d","current_value":0,"previous_value":5747.7,
  "method":"rule_based","severity":"high",
  "description":f"THE BID WENT BACK TO ZERO - RUN #20's REACTIVATION WAS A MAINTENANCE TRANSFER, EXACTLY AS PRE-REGISTERED. Run #20 wrote the test in advance: a tranche in the 30-50K range would mean the bid is genuinely back; 'another sub-10K week or a return to zero = this was a maintenance transfer and the dormancy finding should be revived'. It returned to zero. The Mega Whale absorber erd18mv2z6r2 recorded ZERO transactions (balance {f(bid['mega_balance'])}, {bid['mega_change']:+.2f} EGLD - dust), and the Coinbase Routing wallet that fed it also recorded zero, sitting at {f(bid['cb_routing_balance'],1)} EGLD. So the one identifiable large bid on this chain has been absent in {bid['weeks_at_zero_in_last_four']} of the last 4 weeks and its single active week moved {f(5747.7)} EGLD. Bid dormancy is promoted back to a structural finding: the chain has no nameable large buyer of size. The mitigating fact this week is that it did not need one - the OTC feed switched off at the same time."},
 {"metric":"egld_price_usd","current_value":price,"previous_value":M["prev_price"],"method":"z_score",
  "average_value":z["price"][0],"stddev":z["price"][1],"z_score":z["price"][2],"severity":"low",
  "description":f"EGLD {pc:+.2f}% to ${price:.2f} while BTC {M['btc_wow']:+.2f}% and ETH {M['eth_wow']:+.2f}% - the first EGLD-SPECIFIC OUTPERFORMANCE since run #16, and it happened in the week the OTC feed switched off. z={z['price'][2]:+.2f}sigma is uninformative on a move this size. The pairing is the point: run #20 had a tripling of net distribution and a flat tape; this week the feed collapsed {100*(otc['upbit_feed']-otc['prev_upbit_feed'])/otc['prev_upbit_feed']:+.0f}% and price took +3% with BTC slightly negative. Two weeks is not a regime, and the demand instruments are still weak in absolute terms (turnover {xx['turnover_ratio_pct']:.2f}% of pool TVL, identifiable bid zero), so the honest reading is that removing supply pressure was sufficient for a 3% week - which says the marginal seller, not the marginal buyer, has been setting this price."},
 {"metric":"usdt_supply_burn","current_value":df["usdt_supply_wow"],"previous_value":-1.02,
  "method":"rule_based","severity":"high",
  "description":f"BRIDGED USDT SUPPLY FELL {df['usdt_supply_wow']:+.2f}% - {f(df['usdt_supply_prev']-df['usdt_supply'])} TOKENS REDEEMED, THE LARGEST STABLECOIN CONTRACTION IN TRACKING. Supply went {f(df['usdt_supply_prev'])} -> {f(df['usdt_supply'])} in seven days, against a prior worst week of -3.7% (run #14). USDC fell a further {df['usdc_supply_wow']:+.2f}% to {f(df['usdc_supply'])}. On a base this small the absolute dollar number (~$100K) is not systemic, but the direction is: dollars have now left the chain for nine consecutive runs with no inflow week, and this is the sharpest single-week exit of the series. It is also the one signal that points the opposite way from the price action and the DEX recovery this week, which is why it belongs in the TL;DR rather than in a footnote."},
 {"metric":"binance_staking_custody_egld","current_value":round(cust["balance"]),
  "previous_value":round(cust["prev"]),"method":"rule_based","severity":"medium",
  "description":f"BINANCE RE-PARKED {f(cust['change'])} EGLD FROM ITS HOT WALLET INTO STAKING CUSTODY - the first custody movement in three weeks, and traceable as a single standard transfer on 2026-08-14 from Binance.com hot (which fell {f(-127064)} in the same window). Custody is now {f(cust['balance'])}, {cust['from_peak']:+,.0f} from the 3,512,650 peak. It was NOT delegated - the balance holds the full amount and the binance_staking PROVIDER moved only {sk['binance_staking_prov_wow']:+,.0f}. Per the branches registered in run #15 and carried since: a drawdown to hot wallets = distribution; a re-delegation = the first constructive Binance signal in six runs. This is the third possibility - re-parking - and on the supply side it is mildly constructive, because 118,440 EGLD moved out of the wallet Binance sells from into the wallet it stakes from. It is the same shape as the runs #7-#10 accumulation phase, which ended in a drawdown, so it is not evidence of intent."},
 {"metric":"dex_turnover_ratio_pct","current_value":xx["turnover_ratio_pct"],
  "previous_value":xx["previous_turnover_ratio_pct"],"method":"rule_based","severity":"medium",
  "description":f"TURNOVER ROSE A SECOND WEEK, {xx['previous_turnover_ratio_pct']:.2f}% -> {xx['turnover_ratio_pct']:.2f}% of pool TVL traded daily, on volume ${xx['total_volume_24h_usd']/1000:.1f}K ({xx['dex_vol_wow_pct']:+.1f}%) and near-flat depth (${xx['pool_tvl_usd']/1e6:.2f}M, {100*(xx['pool_tvl_usd']-xx['previous_pool_tvl_usd'])/xx['previous_pool_tvl_usd']:+.1f}%). The series is now 4.06 / 2.14 / 2.24 / {xx['turnover_ratio_pct']:.2f} - the two-week halving reversed and the level is back to roughly three-quarters of where the collapse started. Run #19's ~4% threshold for calling the bid back is still unmet, but this is the first two-week improvement in the demand instruments since they were built. Concentration remains {xx['top_pair_dominance_pct']:.1f}% in WEGLD/USDC."},
 {"metric":"mex_pair_depth_checked","current_value":xx["mex_pair_depth"]["tvl_usd"],
  "previous_value":None,"method":"rule_based","severity":"medium",
  "description":f"MEX's OUTPERFORMANCE IS REAL PRICE ACTION, NOT STALE PRICING - closing run #20 recommendation #8 and correcting two runs of assumption. Runs #19 and #20 both attributed MEX beating EGLD to 'stale pricing in illiquid pairs' without checking. Checked: the MEX/WEGLD pair holds ${xx['mex_pair_depth']['tvl_usd']:,.0f} of pool TVL - {xx['mex_pair_depth']['share_of_pool_tvl_pct']:.1f}% of ALL xExchange depth and the #{xx['mex_pair_depth']['depth_rank']} deepest pool on the DEX - and traded {xx['mex_pair_depth']['trades_24h']} times in 24h. That is thin in volume (${xx['mex_pair_depth']['volume_24h_usd']:,.0f}) but it is not an unpriced pair. MEX is now {xx['mex_price_change_wow_pct']:+.2f}% WoW against EGLD's {pc:+.2f}%, a fourth consecutive week of MEX >= EGLD, and the stale-pricing explanation is withdrawn. What remains is a real question the model cannot yet answer: why the DEX token is leading the chain's native asset through a distribution episode."},
 {"metric":"xegld_redemption_destination_traced","current_value":df["xegld_supply_wow"],
  "previous_value":-2.23,"method":"rule_based","severity":"low",
  "description":f"THE XEGLD REDEMPTION IS RETAIL-SCALE ROTATION, NOT AN EXIT (closes run #20 recommendation #3). XEGLD supply fell a further {df['xegld_supply_wow']:+.2f}% to {f(df['xegld_supply'])} - decelerating from last week's -2.23%. The XOXNO LSD contract itself has ZERO outbound value transactions (it pays out via smart-contract results, the run #15/#19 pattern), so the trace ran through the callers instead: {O['xegld_trace']['fn_counts']['unDelegate']} unDelegate, {O['xegld_trace']['fn_counts']['unDelegatePending']} unDelegatePending, {O['xegld_trace']['fn_counts']['withdraw']} withdraw and {O['xegld_trace']['fn_counts']['withdrawPending']} withdrawPending calls across {O['xegld_trace']['callers']} distinct wallets. Their onward flows total roughly {f(O['xegld_trace']['other_egld']+O['xegld_trace']['delegation_egld'])} EGLD, of which {f(O['xegld_trace']['delegation_egld'])} went into NATIVE DELEGATION contracts and ZERO to any labelled exchange - the rest went to unlabeled wallets and one game contract, in 80-600 EGLD amounts. Per run #20's pre-commitment, that is the constructive/idiosyncratic branch: no exchange destination, some migration to native staking, no single large redeemer."},
 {"metric":"reward_compound_rate","current_value":rw["compound_pct"],"previous_value":rw["compound_prev"],
  "method":"rule_based","severity":"low",
  "description":f"COMPOUNDING FLAT AT {rw['compound_pct']:.2f}% of reward decisions ({rw['redelegate']} reDelegateRewards vs {rw['claims']} claimRewards across the top 8 providers), {rw['compound_pct']-rw['compound_prev']:+.2f}pp WoW and squarely inside the 55-62% band the series has held for eleven runs. Retail is unchanged and remains the most stable measurement in the model: of {rw['retail_n']} retail claims traced, {rw['retail_sold']} went to a labelled exchange, {rw['retail_held']} simply stayed in the claimant's wallet. The only selling cohort was institutional again - {rw['inst_n']} events, {f(rw['inst_val'])} EGLD, of which {f(rw['inst_sold_val'])} ({100*rw['inst_sold_val']/rw['inst_val']:.0f}%) went to an exchange."},
 {"metric":"total_delegators","current_value":sk["churn"]["total_delegators_current"],
  "previous_value":sk["churn"]["total_delegators_previous"],"method":"z_score",
  "average_value":z["deleg"][0],"stddev":z["deleg"][1],"z_score":z["deleg"][2],"severity":"low",
  "description":f"Delegators {sk['churn']['total_delegators_current']:,} ({sk['churn']['delegators_added']:+}), a 9th consecutive flat week on a ~174.3K base. Structural since run #18 and recorded rather than narrated; z={z['deleg'][2]:+.2f}sigma with the run #9 degenerate-z guard applying. Worth one observation this week only because of where the incentive was: two providers set a 100% fee, meaning their delegators earn literally nothing, and the user counts moved by {F1['users_wow']:+d} and {F2['users_wow']:+d}. If a zero-yield signal does not move retail, nothing in the current fee range will."},
 {"metric":"staked_egld","current_value":staked,"previous_value":pecon["staked_egld"],"method":"z_score",
  "average_value":z["staked"][0],"stddev":z["staked"][1],"z_score":z["staked"][2],"severity":"low",
  "description":f"Total staked {staked:,} EGLD ({M['staked_chg']:+,}), staked ratio {M['sr']*100:.2f}% ({100*(M['sr']-M['sr_prev']):+.2f}pp), z={z['staked'][2]:+.2f}sigma. Delegation TVL FELL {sk['deleg_tvl_wow']:+,.0f} to {f(sk['total_locked'])}, but {UNW['share_of_delegation_decline_pct']:.0f}% of that decline is the single wallet unwinding {f(UNW['total'])} across two providers. Ex-that-wallet delegation was roughly {sk['deleg_tvl_wow']+UNW['total']:+,.0f} - flat. One provider left the active set entirely (locked 122,947 -> 0, seven users), the first >50K leaver since tracking began."},
 {"metric":"mex_price_usd","current_value":xx["mex_price_usd"],"previous_value":prev["xexchange"]["mex_price_usd"],
  "method":"z_score","average_value":z["mex"][0],"stddev":z["mex"][1],"z_score":z["mex"][2],"severity":"low",
  "description":f"MEX {xx['mex_price_change_wow_pct']:+.2f}% to ${xx['mex_price_usd']:.3e} (z={z['mex'][2]:+.2f}sigma), mcap ${xx['mex_market_cap_usd']/1e6:.2f}M - a fourth consecutive week at or above EGLD. See the pair-depth anomaly: the illiquidity explanation used in runs #19 and #20 does not survive contact with the data."}]

# ------------------------------------------------------------------ trends
accelerating=[
 {"exchange":"UPbit OTC Desks","trend":"outflow","cumulative_change_pct":round(100*otc["desk_delta"]/otc["desk_balance_prev"],1),
  "weeks_in_trend":1,
  "interpretation":f"THE FEED STOPPED. UPbit sent {f(otc['upbit_feed'])} EGLD into the desks against {f(otc['prev_upbit_feed'])} last week ({100*(otc['upbit_feed']-otc['prev_upbit_feed'])/otc['prev_upbit_feed']:+.0f}%), and the desks returned {f(otc['upbit_return'])} to UPbit. Desk balance {otc['desk_delta']:+,.0f} to {f(otc['desk_balance'])}. Gross throughput {f(otc['gross_out'])} ({100*(otc['gross_out']-otc['prev_gross'])/otc['prev_gross']:+.0f}%). Wave #2 measured over its own window (Aug 3-17) delivered {f(wave['net_one_way'])} one-way, about {100*wave['net_one_way']/otc['peak']['net']:.0f}% of the re-netted run #17 peak, and is now unloading rather than loading."},
 {"exchange":"Binance Staking custody","trend":"inflow","cumulative_change_pct":round(100*cust["from_peak"]/3512650.2283337726,1),
  "weeks_in_trend":1,
  "interpretation":f"First movement in three weeks and it is a RELOAD: {f(cust['change'])} EGLD from Binance.com hot in one traceable standard transfer, custody now {f(cust['balance'])} ({cust['from_peak']:+,.0f} from the peak). Not delegated. Constructive on the supply side (coins moved out of the sell-side wallet) but structurally identical to the runs #7-#10 accumulation phase, which ended in a drawdown."},
 {"exchange":"NET_EXCHANGE","trend":"inflow","cumulative_change_pct":round(100*ex["net_total"]/ex["total_prev"],2),
  "weeks_in_trend":2,
  "interpretation":f"Net {ex['net_total']:+,.0f} EGLD across tracked exchange wallets - flat to three significant figures and the smallest net move in the tracked series. Bybit {ex['ent_cur'].get('Bybit',0)-ex['ent_prev'].get('Bybit',0):+,.0f} (5th inflow week) and Gate.io {ex['ent_cur'].get('Gate.io',0)-ex['ent_prev'].get('Gate.io',0):+,.0f} in; Coinbase {ex['ent_cur'].get('Coinbase',0)-ex['ent_prev'].get('Coinbase',0):+,.0f}, UPbit {ex['ent_cur'].get('UPbit',0)-ex['ent_prev'].get('UPbit',0):+,.0f} and Binance {ex['ent_cur'].get('Binance',0)-ex['ent_prev'].get('Binance',0):+,.0f} out. The Binance figure is intra-entity plumbing (hot -> custody), so per the run #15 rule it should not be read as a flow at all."},
 {"exchange":"Bybit","trend":"inflow","cumulative_change_pct":6.1,"weeks_in_trend":5,
  "interpretation":f"5th consecutive inflow week ({ex['ent_cur'].get('Bybit',0)-ex['ent_prev'].get('Bybit',0):+,.0f} to {f(ex['ent_cur'].get('Bybit',0))}) and again roughly half of it is hub output: Bybit took {f(otc['outbound_by_venue'].get('Bybit',0))} out of the desks through routers against {f(otc['inbound_by_venue'].get('Bybit',0))} fed in, net {hn.get('Bybit',0):+,.0f}. Five weeks makes this the longest single-venue inflow streak in tracking."}]

streaks=[
 {"metric":"otc_net_one_way_distribution","direction":"down","weeks":1,
  "cumulative_change_pct":round(100*(otc["net_one_way"]-otc["prev_net"])/otc["prev_net"],1),
  "interpretation":f"Weekly net one-way {f(otc['prev_net'])} -> {f(otc['net_one_way'])}, but the weekly frame is the wrong unit for a wave that spans weeks: netted across Aug 3-17 the whole episode is {f(wave['net_one_way'])}, not the {f(wave['sum_of_weekly_nets'])} the two weekly figures sum to. The feed itself is the leading indicator and it fell {100*(otc['upbit_feed']-otc['prev_upbit_feed'])/otc['prev_upbit_feed']:+.0f}%."},
 {"metric":"dex_turnover_ratio_pct","direction":"up","weeks":2,
  "cumulative_change_pct":round(100*(xx["turnover_ratio_pct"]-2.141)/2.141,1),
  "interpretation":f"Second consecutive rise (2.14 -> 2.24 -> {xx['turnover_ratio_pct']:.2f}%) on volume +{xx['dex_vol_wow_pct']:.0f}% and flat depth. The first two-week improvement in any demand instrument since they were built in run #19; still below the ~4% level that would evidence a returning bid."},
 {"metric":"mex_outperforming_egld","direction":"up","weeks":4,"cumulative_change_pct":None,
  "interpretation":f"MEX has matched or beaten EGLD for four straight weeks ({xx['mex_price_change_wow_pct']:+.2f}% vs {pc:+.2f}% this week). The stale-pricing explanation is now falsified - MEX/WEGLD is the #2 deepest pool on the DEX at ${xx['mex_pair_depth']['tvl_usd']:,.0f} with {xx['mex_pair_depth']['trades_24h']} trades in 24h."},
 {"metric":"bridged_stablecoin_outflow","direction":"down","weeks":9,"cumulative_change_pct":None,
  "interpretation":f"Ninth consecutive run without an inflow week, and the sharpest exit of the series: USDT {df['usdt_supply_wow']:+.2f}% ({f(df['usdt_supply_prev']-df['usdt_supply'])} tokens), USDC {df['usdc_supply_wow']:+.2f}%. WEGLD supply was flat ({df['wegld_supply_wow']:+.2f}%)."},
 {"metric":"delegator_base_flat","direction":"flat","weeks":9,"cumulative_change_pct":0,
  "interpretation":f"9th flat week ({sk['churn']['delegators_added']:+} on {sk['churn']['total_delegators_current']:,}). Structural since run #18. This week it survived a zero-yield signal at two providers, which is the strongest test it has faced."},
 {"metric":"identifiable_bid_dormant","direction":"flat","weeks":3,"cumulative_change_pct":None,
  "interpretation":f"Zero absorption in 3 of the last 4 weeks; the one active week moved 5,748 EGLD. Run #20's pre-registered sub-10K branch fired, so the dormancy finding is revived as structural."},
 {"metric":"token_holder_count_decline","direction":"down","weeks":21,"cumulative_change_pct":None,
  "interpretation":"21st consecutive week of small holder declines across the top-10 tokens - the established airdrop-decay baseline, not a signal."}]

regimes=[
 {"metric":"otc_netting_window_must_match_the_wave","before_value":round(wave["sum_of_weekly_nets"]),
  "after_value":round(wave["net_one_way"]),
  "description":f"A METHODOLOGICAL LEVEL CHANGE, and the most consequential result of this run. Circularity does not respect week boundaries: UPbit fed 319,000 into the desks in the Aug 3-10 window and took {f(otc['upbit_return'])} back in the Aug 10-17 window, so each week's netting counts a leg whose mirror sits in the adjacent week. Summing weekly nets across the wave gives {f(wave['sum_of_weekly_nets'])}; netting the wave as one window gives {f(wave['net_one_way'])}, an overstatement of {wave['overstatement_pct']:.0f}%. RULE: net over the WAVE (feed-to-drain), not the reporting week, and treat the weekly net one-way as an upper bound. The five-anchor backfilled series remains valid for weeks where feed and drain fell inside the same window - which is most of them, since circularity there measured {otc['run16']['circ_pct']:.0f}-{otc['circ_series_pct']['run19']:.0f}%."},
 {"metric":"direct_node_unwind_withdrawn","before_value":-215000,"after_value":round(sk["corrected_direct"]),
  "description":f"A three-run narrative is withdrawn. The 'direct-node unwind' (~215K over runs #18-#20, described in run #20 as 'the largest unexplained structural flow tracked') was measured as a residual that also absorbs delegation-layer unbonding in flight. This week that residual flipped to {sk['raw_direct_residual']:+,.0f} and {f(UNW['total'])} of it is one wallet's unDelegate pair, still unbonding. Corrected, direct-node stake GREW {sk['corrected_direct']:+,.0f}. RULE: the staked-minus-delegated residual is a direct-node PLUS unbonding-pool measure; decompose it against /accounts/{{addr}}/delegation before attributing it to node operators. The protocol Staking SC itself is not queryable for transactions (HTTP 400 on every variant tried), so this is the only available route."},
 {"metric":"delegation_market_fee_repricing_withdrawn","before_value":F1["fee_from_pct"] if F1 else None,
  "after_value":100,
  "description":(f"Run #20's 'first competitive fee cut in twenty runs' is withdrawn one week later. egldstakingprovider moved 15% -> 100% and procryptostaking 20% -> 100%, both zeroing delegator APR, both with 50 nodes still running, both under different owners. What looked like the delegation market finally responding to fee arbitrage was the start of two operators exiting or squeezing their books. The yield-arbitrage mechanism still describes where stake GOES ({sk['hi_apr_n']} providers at APR >= 8.8% took {sk['hi_apr_net']:+,.0f} net, zero-fee providers {sk['zero_fee_net']:+,.0f}), but it does not predict incumbent behaviour, and a fee change is not evidence of competition."
   ) if F1 and F2 else "No fee repricing this week."}]

trend_indicators={"accelerating_exchange_outflows":accelerating,
 "validator_movements":{"providers_joining":0,"providers_leaving":len(sk["leavers"]),
   "net_provider_change":sk["n_providers"]-len(prev["staking_providers"]),
   "notable_joiners":[],"notable_leavers":sk["notable_leavers"]},
 "token_supply_events":O["token_supply_events"],
 "consecutive_streaks":streaks,"regime_shifts":regimes}

json.dump({"anomalies":anomalies,"trend_indicators":trend_indicators},
          open("/tmp/run21w/part3.json","w"),indent=1)
print("STAGE 3 OK  anomalies",len(anomalies),"streaks",len(streaks),"regimes",len(regimes))
