#!/usr/bin/env python3
"""Run #21 stage 4: narratives + final report write."""
import json
from datetime import datetime, timezone

REPO="/Users/ls/Documents/MultiversX/projects/onchain-quant-agent"
O=json.load(open("/tmp/run21w/derived.json"))
P3=json.load(open("/tmp/run21w/part3.json"))
D=json.load(open(f"{REPO}/data/collected/2026-08-17.json"))
prev=json.load(open(f"{REPO}/data/previous.json"))
status=json.load(open("/tmp/run21w/status.json"))

M=O["macro"]; otc=O["otc"]; wave=otc["wave"]; bid=O["bid"]; ex=O["exch"]; cust=O["custody"]
sk=O["staking"]; rw=O["reward"]; tk=O["tokens"]; xx=O["xexchange"]; df=O["defi"]
wi=O["whale_i"]; z=O["z"]; br=O["breadth"]
econ=D["economics"]; st=D["stats"]; pecon=prev["economics"]; pact=prev["activity"]
price=M["price"]; pc=M["price_chg"]; staked=M["staked"]
FEE=sk["fee_events"]; F1=FEE[0]; F2=FEE[1]
UNW=sk["unwind"]; hn=otc["net_by_venue"]
def f(x,d=0): return f"{x:,.{d}f}"
tr=df["transfers"]

# ---------------- exchange flows object ----------------
ent_interp={
 "Bybit":f"{ex['ent_cur'].get('Bybit',0)-ex['ent_prev'].get('Bybit',0):+,.0f} (+6.1%) to {f(ex['ent_cur'].get('Bybit',0))} - a FIFTH consecutive inflow week, the longest single-venue streak in tracking. Roughly half is hub output rather than customer deposits: Bybit took {f(otc['outbound_by_venue'].get('Bybit',0))} out of the desks through routers against {f(otc['inbound_by_venue'].get('Bybit',0))} fed in (net {hn.get('Bybit',0):+,.0f}).",
 "UPbit":f"{ex['ent_cur'].get('UPbit',0)-ex['ent_prev'].get('UPbit',0):+,.0f} to {f(ex['ent_cur'].get('UPbit',0))}, and the balance is now the least interesting thing about UPbit. It fed the OTC desks only {f(otc['upbit_feed'])} EGLD this week against 319,000 last week, and took {f(otc['upbit_return'])} back OUT of them - so over the two-week wave window UPbit is a net source of {f(abs(wave['net_by_venue'].get('UPbit',0)))} rather than the -319,000 the weekly frame showed. Its 30-day inbound is itself dominated by the desks and their feeders, which answers run #20's 'what replenishes UPbit' question: the hub does.",
 "Coinbase":f"{ex['ent_cur'].get('Coinbase',0)-ex['ent_prev'].get('Coinbase',0):+,.0f} (-6.9%) across {ex['ent_w'].get('Coinbase',1)} wallets. The Coinbase Routing wallet that fed the absorber last week did nothing at all ({f(bid['cb_routing_balance'],1)} EGLD, zero transactions), so unlike run #20 none of this outflow is the bid pipe. Coinbase Custody 2 also released 10,000.",
 "Binance":f"Net {ex['ent_cur'].get('Binance',0)-ex['ent_prev'].get('Binance',0):+,.0f} across {ex['ent_w'].get('Binance',1)} wallets, which per the run #15 entity rule is NOT a flow: the Binance.com hot wallet fell {f(-127064)} and the Staking custody wallet rose {f(cust['change'])} in a single traceable standard transfer on 2026-08-14. Intra-entity plumbing. Custody now {f(cust['balance'])}, {cust['from_peak']:+,.0f} from the 3,512,650 peak, and NOT delegated - the binance_staking provider moved only {sk['binance_staking_prov_wow']:+,.0f}. Binance.com remains the largest net RECEIVER from the OTC hub ({hn.get('Binance.com',0):+,.0f} this week, {wave['net_by_venue'].get('Binance.com',0):+,.0f} over the wave window).",
 "Gate.io":f"{ex['ent_cur'].get('Gate.io',0)-ex['ent_prev'].get('Gate.io',0):+,.0f} (+9.5%) to {f(ex['ent_cur'].get('Gate.io',0))}, with hub participation almost perfectly balanced this week ({f(otc['outbound_by_venue'].get('Gate.io',0))} out, {f(otc['inbound_by_venue'].get('Gate.io',0))} in, net {hn.get('Gate.io',0):+,.0f}) - the cleanest example of the circular pattern the netting was built to strip out.",
 "Crypto.com":f"{ex['ent_cur'].get('Crypto.com',0)-ex['ent_prev'].get('Crypto.com',0):+,.0f} (+2.4%). No pipeline involvement.",
 "KuCoin":f"{ex['ent_cur'].get('KuCoin',0)-ex['ent_prev'].get('KuCoin',0):+,.0f} (-1.3%) to {f(ex['ent_cur'].get('KuCoin',0))} - the run #17 whale deposit is still sitting there, down only 3.9% in five weeks.",
 "Bitget":f"{ex['ent_cur'].get('Bitget',0)-ex['ent_prev'].get('Bitget',0):+,.0f} (+3.9%). Small base.",
 "MEXC":f"{ex['ent_cur'].get('MEXC',0)-ex['ent_prev'].get('MEXC',0):+,.0f} (-0.05%). Flat."}
entity_netting=[]
for e in sorted(ex["ent_cur"], key=lambda k:-abs(ex["ent_cur"][k]-ex["ent_prev"].get(k,0))):
    net=ex["ent_cur"][e]-ex["ent_prev"].get(e,0)
    entity_netting.append({"entity":e,"wallets_count":ex["ent_w"].get(e,1),"net_flow_egld":net,
        "interpretation":ent_interp.get(e,f"Net change: {net:+.0f} EGLD")})
exchange_flows={"total_exchange_egld_current":ex["total_cur"],"total_exchange_egld_previous":ex["total_prev"],
 "net_change_egld":ex["net_total"],"net_change_pct":100*ex["net_total"]/ex["total_prev"],
 "direction":"inflow" if ex["net_total"]>0 else "outflow",
 "signal":f"Net exchange flow {ex['net_total']:+,.0f} EGLD ({100*ex['net_total']/ex['total_prev']:+.2f}%) - the smallest net move in the tracked series, and genuinely uninformative rather than merely quiet. Two things cancel inside it. First, Binance's {ex['ent_cur'].get('Binance',0)-ex['ent_prev'].get('Binance',0):+,.0f} is intra-entity: hot -127,064 into custody +{f(cust['change'])}, one standard transfer, no external flow (run #15 rule). Second, Bybit's {ex['ent_cur'].get('Bybit',0)-ex['ent_prev'].get('Bybit',0):+,.0f} is roughly half hub output rather than customer deposit (run #14 joint-read rule). Netting both out, external flow is within a few thousand EGLD of zero. The informative channel this week was the OTC feed, and it switched off: UPbit sent {f(otc['upbit_feed'])} EGLD to the desks against 319,000 last week and took {f(otc['upbit_return'])} back. Six addresses that had no prior-week balance were excluded from the delta per the run #18 rule ({', '.join(x['label'] for x in ex['no_prior'][:4])} and 3 more), so no phantom inflow is embedded in the headline.",
 "by_exchange":ex["by_exchange"],"entity_netting":entity_netting}

# ---------------- protocol breakdown ----------------
protocol_breakdown=[
 {"protocol":"xExchange","category":"dex","addresses_tracked":16,"tvl_usd":df["xexch_tvl_usd"],
  "tvl_egld":df["xexch_tvl_egld"],"tvl_wow_change_pct":df["xexch_egld_wow_pct"],"transfers_24h":None,
  "volume_24h_usd":xx["total_volume_24h_usd"],
  "notable_events":f"TURNOVER ROSE A SECOND WEEK: {xx['previous_turnover_ratio_pct']:.2f}% -> {xx['turnover_ratio_pct']:.2f}% of pool TVL traded daily, on volume ${xx['total_volume_24h_usd']/1000:.1f}K ({xx['dex_vol_wow_pct']:+.1f}%) and depth ${xx['pool_tvl_usd']/1e6:.2f}M ({100*(xx['pool_tvl_usd']-xx['previous_pool_tvl_usd'])/xx['previous_pool_tvl_usd']:+.1f}%). The series reads 4.06 / 2.14 / 2.24 / {xx['turnover_ratio_pct']:.2f} - the collapse has reversed about three-quarters of the way, still short of the ~4% level run #19 registered as evidence of a returning bid. WEGLD supply flat ({df['wegld_supply_wow']:+.2f}%). Concentration {xx['top_pair_dominance_pct']:.1f}% WEGLD/USDC; the #2 pair is MEX/WEGLD, which this run measured directly at ${xx['mex_pair_depth']['tvl_usd']:,.0f} of depth ({xx['mex_pair_depth']['share_of_pool_tvl_pct']:.1f}% of the DEX) on {xx['mex_pair_depth']['trades_24h']} trades.","health_signal":"growing"},
 {"protocol":"Hatom Lending","category":"lending","addresses_tracked":13,"tvl_usd":df["hatom_lending_usd"],
  "tvl_egld":df["hatom_lending_egld"],"tvl_wow_change_pct":df["hatom_lending_egld_wow_pct"],
  "transfers_24h":tr.get("Hatom EGLD MM"),
  "notable_events":f"TVL ${df['hatom_lending_usd']/1e6:.2f}M USD ({100*(df['hatom_lending_usd']-df['prev_hl_usd'])/df['prev_hl_usd']:+.1f}%), {df['hatom_lending_egld']/1000:.0f}K EGLD ({df['hatom_lending_egld_wow_pct']:+.2f}% EGLD) - the three-week EGLD-denominated deposit growth streak ENDED, with a small withdrawal against a rising price. BILATERAL INVERSE RULE NOT EVALUABLE: price moved {pc:+.2f}%, inside the |5%| guardrail, so the mechanical ratio of {df['inverse_ratio_mechanical']:.2f} is a small-denominator artifact and is explicitly NOT recorded as a confirmation. The series stays at 7 (down-week 0.88 / 0.80 / 0.70 / 0.21 / 0.98 / 0.58; up-week 0.49 / 0.72). Directionally the sign is at least consistent with the rule - deposits shrank in EGLD terms as price rose.","health_signal":"flat"},
 {"protocol":"Hatom Liquid Staking","category":"liquid_staking","addresses_tracked":2,
  "tvl_usd":df["hatom_lsd_usd"],"tvl_egld":df["hatom_lsd_egld"],
  "tvl_wow_change_pct":df["hatom_lsd_egld_wow_pct"],"transfers_24h":tr.get("Hatom Liquid Staking"),
  "notable_events":f"SEGLD ${df['segld_mcap']/1e6:.2f}M + SWTAO ${df['swtao_mcap']/1e6:.2f}M = ${df['hatom_lsd_usd']/1e6:.2f}M ({100*(df['hatom_lsd_usd']-df['prev_hlsd_usd'])/df['prev_hlsd_usd']:+.1f}% USD). On the supply basis (run #13 rule) Hatom LSD is FLAT for a fourth consecutive week: SEGLD {df['segld_supply_wow']:+.3f}% to {f(df['segld_supply'])} and SWTAO {df['swtao_supply_wow']:+.2f}%. Four drawdown-or-flat weeks and then a +3% week have produced no measurable redemption or subscription on the largest LSD - it is the most inert instrument the model tracks.","health_signal":"flat"},
 {"protocol":"Hatom USH","category":"stablecoin","addresses_tracked":4,"tvl_usd":df["ush_usd"],
  "tvl_egld":df["ush_egld"],"tvl_wow_change_pct":100*(df["ush_usd"]-df["prev_ush_usd"])/df["prev_ush_usd"],
  "transfers_24h":None,
  "notable_events":f"USH supply {df['ush_supply_wow']:+.3f}% to {f(df['ush_supply'])} - a second consecutive week inside the noise band, so the run #19-#20 de-leveraging is confirmed complete and NOT followed by re-leveraging. Borrowers retired the run #16 +6.49% chase and have now sat still for two weeks through a +3% price week, which is the more informative half: CDP borrowers did not chase this rally. Per the run #16 mirror rule, a MINT week above +5% would be the signal that leverage is genuinely returning.","health_signal":"flat"},
 {"protocol":"XOXNO LSD","category":"liquid_staking","addresses_tracked":2,"tvl_usd":df["xoxno_lsd_usd"],
  "tvl_egld":df["xoxno_lsd_egld"],"tvl_wow_change_pct":df["xoxno_lsd_egld_wow_pct"],
  "transfers_24h":tr.get("XOXNO LSD"),
  "notable_events":f"XEGLD supply {df['xegld_supply_wow']:+.2f}% to {f(df['xegld_supply'])} (${df['xoxno_lsd_usd']/1e6:.2f}M, {100*(df['xoxno_lsd_usd']-df['prev_xoxno_usd'])/df['prev_xoxno_usd']:+.1f}% USD) - redemption continued for a second week but DECELERATED from -2.23%. DESTINATION NOW TRACED (run #20 recommendation #3): the LSD contract has zero outbound value transactions because it pays via SC results, so the trace ran through the callers - {O['xegld_trace']['fn_counts']['unDelegate']} unDelegate, {O['xegld_trace']['fn_counts']['unDelegatePending']} unDelegatePending, {O['xegld_trace']['fn_counts']['withdraw']} withdraw and {O['xegld_trace']['fn_counts']['withdrawPending']} withdrawPending calls from {O['xegld_trace']['callers']} wallets, whose onward flows are 80-600 EGLD each, {f(O['xegld_trace']['delegation_egld'])} EGLD into native delegation contracts and ZERO to any labelled exchange. Retail-scale rotation, not an exit - the constructive branch of the pre-commitment.","health_signal":"shrinking"},
 {"protocol":"XOXNO Aggregator","category":"aggregator","addresses_tracked":1,"tvl_usd":None,"tvl_egld":None,
  "tvl_wow_change_pct":None,"transfers_24h":tr.get("XOXNO Aggregator"),
  "notable_events":f"{tr.get('XOXNO Aggregator'):,} daily transfers, down from last week's spike but still the highest single-contract routing throughput on the network. Routing and DEX turnover moved in opposite directions this week, which weakens the read-through either way.","health_signal":"flat"},
 {"protocol":"OneDex","category":"aggregator","addresses_tracked":5,"tvl_usd":None,"tvl_egld":None,
  "tvl_wow_change_pct":None,"transfers_24h":tr.get("OneDex Swap"),
  "notable_events":f"{tr.get('OneDex Swap'):,} daily transfers via the swap contract.","health_signal":"flat"},
 {"protocol":"JEXchange","category":"dex","addresses_tracked":4,"tvl_usd":None,"tvl_egld":None,
  "tvl_wow_change_pct":None,"transfers_24h":tr.get("JEXchange Fees"),
  "notable_events":f"Fees wallet {tr.get('JEXchange Fees'):,} daily transfers. The aggregator contract returned 0 transfers in the 24h window - queried successfully, genuinely idle.","health_signal":"flat"}]
protocols=[
 {"name":"xExchange","category":"dex","volume_24h_usd":xx["total_volume_24h_usd"],"active_pairs":25,
  "transfers_24h":None,"tvl_usd":df["xexch_tvl_usd"],"tvl_egld":df["xexch_tvl_egld"],
  "tvl_wow_change_pct":df["xexch_egld_wow_pct"]},
 {"name":"Hatom Lending","category":"lending","volume_24h_usd":None,"active_pairs":None,
  "transfers_24h":tr.get("Hatom EGLD MM"),"tvl_usd":df["hatom_lending_usd"],
  "tvl_egld":df["hatom_lending_egld"],"tvl_wow_change_pct":df["hatom_lending_egld_wow_pct"]},
 {"name":"Hatom Liquid Staking","category":"liquid_staking","volume_24h_usd":None,"active_pairs":None,
  "transfers_24h":tr.get("Hatom Liquid Staking"),"tvl_usd":df["hatom_lsd_usd"],
  "tvl_egld":df["hatom_lsd_egld"],"tvl_wow_change_pct":df["hatom_lsd_egld_wow_pct"]},
 {"name":"XOXNO LSD","category":"liquid_staking","volume_24h_usd":None,"active_pairs":None,
  "transfers_24h":tr.get("XOXNO LSD"),"tvl_usd":df["xoxno_lsd_usd"],"tvl_egld":df["xoxno_lsd_egld"],
  "tvl_wow_change_pct":df["xoxno_lsd_egld_wow_pct"]}]

# ---------------- executive summary ----------------
executive_summary=[
 {"finding":f"WAVE #2 DID NOT ESCALATE - THE FEED SWITCHED OFF, AND MEASURING THE WAVE PROPERLY CUTS IT BY {wave['overstatement_pct']:.0f}%. Run #20 pre-registered net one-way above ~300,000 on a UPbit tranche above ~350,000 as the escalation test. Neither fired: UPbit sent {f(otc['upbit_feed'])} EGLD to the desks ({100*(otc['upbit_feed']-otc['prev_upbit_feed'])/otc['prev_upbit_feed']:+.0f}% vs last week's 319,000) and the desks pushed {f(otc['upbit_return'])} BACK to UPbit. The weekly figure is {f(otc['net_one_way'])} one-way on {f(otc['gross_out'])} gross, but netting the WHOLE wave window (Aug 3-17) gives {f(wave['net_one_way'])} against {f(wave['sum_of_weekly_nets'])} from summing the two weekly nets - because circularity crosses week boundaries. Wave #2 delivered roughly {100*wave['net_one_way']/otc['peak']['net']:.0f}% of the re-netted run #17 peak and is now unloading. Terminals over the wave: Binance.com {wave['net_by_venue'].get('Binance.com',0):+,.0f}, Bybit {wave['net_by_venue'].get('Bybit',0):+,.0f}.","severity":"critical","category":"whale"},
 {"finding":f"THE THREE-WEEK 'DIRECT-NODE UNWIND' WAS A MEASUREMENT ARTIFACT AND IS WITHDRAWN. Run #20 called it 'the largest unexplained structural flow tracked' (~215K over three weeks). The residual it was measured from - total staked minus summed provider locked - also absorbs delegation unbonding in flight, because an unDelegate removes EGLD from provider 'locked' immediately while it stays in the staking module for 7-10 epochs. This week the residual flipped to {sk['raw_direct_residual']:+,.0f} and ONE wallet accounts for {f(UNW['total'])} of it: {f(UNW['legs'][0]['amount'])} unDelegated from p2p_org_ on Aug 15 and {f(UNW['legs'][1]['amount'])} from a second provider on Aug 14, both still unbonding, both zero-value transactions with the amount in the data field. Corrected, direct-node stake GREW {sk['corrected_direct']:+,.0f}. The protocol Staking SC returns HTTP 400 on every transaction-query variant, so /accounts/{{addr}}/delegation is the only route to the unbonding pool - and it must be checked before any residual is attributed to node operators.","severity":"critical","category":"staking"},
 {"finding":f"BOTH HIGH-FEE INCUMBENTS SET SERVICE FEE TO 100%, ZEROING DELEGATOR APR - RUN #20's 'FIRST COMPETITIVE FEE CUT' IS WITHDRAWN. egldstakingprovider went 15% -> 100% one week after the cut run #20 celebrated; procryptostaking went 20% -> 100%. Verified on three endpoints, different owner wallets, 50 nodes each still running. Both kept bleeding ({F1['locked_wow_egld']:+,.0f} EGLD / {F1['users_wow']:+d} users and {F2['locked_wow_egld']:+,.0f} / {F2['users_wow']:+d}). This is a wind-down or a squeeze, not competition, and it means the fee-arbitrage mechanism describes where stake goes ({sk['hi_apr_n']} providers at APR >= 8.8% took {sk['hi_apr_net']:+,.0f}; zero-fee providers {sk['zero_fee_net']:+,.0f}) but says nothing about incumbent behaviour. Note the delegator response: -26% of egldstakingprovider's book left, but only {abs(F1['users_wow'])} of its ~1,124 users - a zero-yield signal moved capital, not people.","severity":"high","category":"staking"},
 {"finding":f"THE IDENTIFIABLE BID RETURNED TO ZERO, EXACTLY AS THE PRE-COMMITMENT SPECIFIED. Run #20 wrote that 'another sub-10K week or a return to zero = this was a maintenance transfer and the dormancy finding should be revived'. The Mega Whale absorber recorded ZERO transactions ({f(bid['mega_balance'])} EGLD, {bid['mega_change']:+.2f}) and the Coinbase Routing pipe that fed it also did nothing, sitting at {f(bid['cb_routing_balance'],1)} EGLD. Bid dormancy is now structural: absent in {bid['weeks_at_zero_in_last_four']} of the last 4 weeks, with one 5,748 EGLD week in between. The chain has no nameable large buyer - it simply did not need one in a week when the OTC feed stopped.","severity":"high","category":"whale"},
 {"finding":f"EGLD OUTPERFORMED FOR THE FIRST TIME SINCE RUN #16: {pc:+.2f}% to ${price:.2f} against BTC {M['btc_wow']:+.2f}% and ETH {M['eth_wow']:+.2f}%. The pairing with the OTC feed collapsing in the same week is the whole story - run #20 had a tripling of distribution and a flat tape, this week has no feed and a +3% tape. It says the marginal SELLER has been setting this price, not the marginal buyer, because the bid was measurably absent again while price rose. Two weeks is not a regime and the demand instruments remain weak in absolute terms (turnover {xx['turnover_ratio_pct']:.2f}% of pool TVL, identifiable bid zero, dollars leaving the chain), so this is supply relief rather than demand arrival.","severity":"high","category":"network"},
 {"finding":f"BRIDGED USDT SUPPLY FELL {df['usdt_supply_wow']:+.2f}% - {f(df['usdt_supply_prev']-df['usdt_supply'])} tokens redeemed, the largest single-week stablecoin contraction in tracking (prior worst -3.7%, run #14). USDC fell a further {df['usdc_supply_wow']:+.2f}%. This is the one instrument pointing the opposite way from the price and DEX recovery: on-chain dollars have now contracted for nine consecutive runs with no inflow week. In absolute terms it is only ~$100K, so the signal is the direction and the persistence, not the size.","severity":"high","category":"token"},
 {"finding":f"BINANCE RE-PARKED {f(cust['change'])} EGLD HOT -> STAKING CUSTODY, the first custody move in three weeks, as one traceable standard transfer on Aug 14 (Binance.com hot -127,064). Custody {f(cust['balance'])} ({cust['from_peak']:+,.0f} from the peak), NOT delegated - the binance_staking provider moved only {sk['binance_staking_prov_wow']:+,.0f}. Neither registered branch (drawdown-to-hot = distribution, re-delegation = constructive) fired; this is the third case, re-parking, which is mildly constructive because the coins left the wallet Binance sells from. It is also structurally identical to the runs #7-#10 accumulation phase that ended in a drawdown, so it is not evidence of intent.","severity":"medium","category":"whale"},
 {"finding":f"THE NET ONE-WAY SERIES NOW HAS FIVE MEASURED ANCHORS AND MEX's OUTPERFORMANCE IS REAL - two closed recommendations. Backfilling run #16 ({f(otc['run16']['gross'])} gross = {f(otc['run16']['net'])} one-way, {otc['run16']['circ_pct']:.0f}% circular) and run #18 ({f(otc['run18']['gross'])} = {f(otc['run18']['net'])}, {otc['run18']['circ_pct']:.0f}%) confirms circularity is roughly constant at 63-80% and gives a comparable series: {f(otc['run16']['net'])} / {f(otc['peak']['net'])} / {f(otc['run18']['net'])} / 61,435 / {f(otc['prev_net'])} / {f(otc['net_one_way'])}. Separately, the 'MEX is stale-priced' explanation used in runs #19 and #20 is falsified: MEX/WEGLD is the #{xx['mex_pair_depth']['depth_rank']} deepest pool on xExchange at ${xx['mex_pair_depth']['tvl_usd']:,.0f} ({xx['mex_pair_depth']['share_of_pool_tvl_pct']:.1f}% of all depth) with {xx['mex_pair_depth']['trades_24h']} trades in 24h. Four straight weeks of MEX >= EGLD is real price action the model cannot yet explain.","severity":"medium","category":"trend"},
 {"finding":f"'UNKNOWN WHALE I' MEETS THE PRE-COMMITTED THRESHOLD FOR RECLASSIFICATION AS OTC OPERATOR INVENTORY. Run #20 set the test at >60% of counterparty value being hub feeders and routers. With the page cap raised, the full 30-day trace ({wi['in_txs']} inbound / {wi['out_txs']} outbound transactions, {wi['in_counterparties']} and {wi['out_counterparties']} distinct counterparties, no page-cap truncation) gives {wi['in_pipeline_pct']:.1f}% of inbound value and {wi['out_pipeline_pct']:.1f}% of outbound value from or to hub infrastructure - {wi['combined_pipeline_pct']:.1f}% combined. It clears the threshold on the combined and inbound bases and marginally misses on outbound alone, so it is classified as operator inventory with that caveat stated. Netting it out reduces this week's one-way figure from {f(otc['net_one_way'])} to {f(otc['net_one_way']-wi['hub_net_this_week'])} - a small correction now, but it also removes a 'buyer' the model might otherwise have counted as demand.","severity":"medium","category":"whale"},
 {"finding":f"DELEGATION TVL FELL {sk['deleg_tvl_wow']:+,.0f} TO {f(sk['total_locked'])} AND ONE WALLET IS {UNW['share_of_delegation_decline_pct']:.0f}% OF IT. Ex-that-wallet, delegation was {sk['deleg_tvl_wow']+UNW['total']:+,.0f} - flat, with the usual rotation underneath (pi-staking {sk['pi_staking_wow']:+,.0f} and {sk['pi_staking_users_wow']:+d} users for a 10th week at 9.23% APR / 0% fee, stakenest {sk['stakenest_wow']:+,.0f}, cslabsio {sk['cslabsio_wow']:+,.0f}, disruptivedigital {sk['disruptive_wow']:+,.0f}). A provider also left the active set entirely (122,947 -> 0 locked, 7 users), the first >50K departure in tracking. Delegators {sk['churn']['total_delegators_current']:,} ({sk['churn']['delegators_added']:+}), a 9th flat week. Compound rate flat at {rw['compound_pct']:.2f}%; of {rw['retail_n']} retail claims traced {rw['retail_sold']} went to an exchange.","severity":"medium","category":"staking"}]

# ---------------- network health ----------------
network_health={
 "economics":{"egld_price_usd":price,"market_cap_usd":econ["marketCap"],"total_supply":econ["totalSupply"],
   "circulating_supply":econ["circulatingSupply"],"staked_egld":staked,"staked_ratio":M["sr"],
   "staking_apr":econ["apr"],"base_apr":econ["baseApr"],"topup_apr":econ["topUpApr"],
   "token_market_cap_usd":econ["tokenMarketCap"]},
 "activity":{"total_accounts":st["accounts"],"total_transactions":st["transactions"],"epoch":st["epoch"],
   "blocks":st["blocks"],"shards":st["shards"],
   "transactions_7d":st["transactions"]-pact["total_transactions"],
   "avg_daily_transactions":round((st["transactions"]-pact["total_transactions"])/7)},
 "deltas":{"price_change_pct":pc,
   "market_cap_change_pct":100*(econ["marketCap"]-pecon["market_cap_usd"])/pecon["market_cap_usd"],
   "staked_ratio_change_pp":100*(M["sr"]-M["sr_prev"]),
   "apr_change_pp":100*(econ["apr"]-pecon["staking_apr"]),
   "accounts_added":st["accounts"]-pact["total_accounts"],
   "btc_correlation_note":f"EGLD {pc:+.2f}% against BTC {M['btc_wow']:+.2f}% and ETH {M['eth_wow']:+.2f}% - the first EGLD-specific OUTPERFORMANCE since run #16's +15.93% decoupling, and a much smaller one. The mechanism is visible rather than inferred this week: the OTC feed that supplied {f(otc['prev_upbit_feed'])} EGLD to the desks last week supplied {f(otc['upbit_feed'])} this week, and the desks returned {f(otc['upbit_return'])} to UPbit. Removing the marginal seller was worth roughly 3pp against a flat tape, with the identifiable bid measurably at zero throughout - which is the cleanest evidence yet that this market has been supply-driven, not demand-starved in the sense of buyers refusing to appear.",
   "transactions_added":st["transactions"]-pact["total_transactions"],
   "supply_added":econ["totalSupply"]-pecon["total_supply"],
   "staked_egld_added":M["staked_chg"],"epoch_advanced":st["epoch"]-pact["epoch"]},
 "analysis":f"EGLD closed at ${price:.2f}, {pc:+.2f}% WoW, while BTC {M['btc_wow']:+.2f}% and ETH {M['eth_wow']:+.2f}% - the first EGLD-specific outperformance in five runs. Market cap ${econ['marketCap']/1e6:.1f}M ({100*(econ['marketCap']-pecon['market_cap_usd'])/pecon['market_cap_usd']:+.1f}%). Usage was steady: {st['transactions']-pact['total_transactions']:,} transactions in the period (~{round((st['transactions']-pact['total_transactions'])/7):,}/day) and {st['accounts']-pact['total_accounts']:,} new accounts across {st['epoch']-pact['epoch']} epochs. Staked EGLD {M['staked_chg']:+,} to {staked:,}, staked ratio {100*(M['sr']-M['sr_prev']):+.2f}pp to {M['sr']*100:.2f}%.\n\nThe substance of this run is corrective. Three of the model's standing claims were tested against deeper measurement and two did not survive: the 'direct-node unwind' carried for three runs is an artifact of a residual that also contains delegation unbonding in flight (one wallet's {f(UNW['total'])} unDelegate pair explains this week's entire flip), and run #20's 'first competitive fee cut in twenty runs' was followed one week later by the same provider setting a 100% fee alongside the other named incumbent. A third - that MEX's outperformance was stale pricing in illiquid pairs - is falsified by direct measurement of the pair's depth. Set against that, the pre-committed tests that were properly specified resolved cleanly: the OTC escalation test failed to fire and the feed collapsed {100*(otc['upbit_feed']-otc['prev_upbit_feed'])/otc['prev_upbit_feed']:+.0f}%, and the bid returned to exactly zero as the sub-10K branch predicted. The most useful new result is methodological: circularity in the OTC hub does not respect week boundaries, so netting must run over the wave (feed-to-drain) rather than the reporting week - which cuts wave #2 from {f(wave['sum_of_weekly_nets'])} to {f(wave['net_one_way'])} of genuine one-way movement and makes every weekly net one-way figure an upper bound."}

# ---------------- analyses ----------------
whale_analysis=f"""The week's flow story is short: the supply stopped arriving, and price went up 3%.

THE FEED SWITCHED OFF. UPbit sent {f(otc['upbit_feed'])} EGLD into the OTC desk complex against {f(otc['prev_upbit_feed'])} the week before, a {100*(otc['upbit_feed']-otc['prev_upbit_feed'])/otc['prev_upbit_feed']:+.0f}% collapse, and the desks sent {f(otc['upbit_return'])} straight back to UPbit. Gross throughput fell to {f(otc['gross_out'])} out / {f(otc['gross_in'])} in ({100*(otc['gross_out']-otc['prev_gross'])/otc['prev_gross']:+.0f}%), desk balance {otc['desk_delta']:+,.0f} to {f(otc['desk_balance'])}. Run #20's pre-committed escalation thresholds (net above ~300,000 AND a tranche above ~350,000) did not fire, and neither did the sub-100K collapse branch on the weekly number - which is itself informative, because it exposed a flaw in the measure.

THE WEEKLY NETTING FRAME IS WRONG FOR A MULTI-WEEK WAVE. This week's weekly net one-way reads {f(otc['net_one_way'])} at only {otc['circ_pct']:.0f}% circularity, against 63-80% in every previously measured window. The reason is mechanical: UPbit's 319,000 feed landed in the Aug 3-10 window and {f(otc['upbit_return'])} of the return leg landed in Aug 10-17, so each week nets against a mirror that sits in the adjacent week. Netting the wave as ONE window (Aug 3-17) gives {f(wave['gross_out'])} gross, {wave['circ_pct']:.0f}% circular, {f(wave['net_one_way'])} genuinely one-way - {wave['overstatement_pct']:.0f}% less than the {f(wave['sum_of_weekly_nets'])} the two weekly figures sum to. On that basis UPbit is a net source of {f(abs(wave['net_by_venue'].get('UPbit',0)))} over the wave and the terminals are Binance.com {wave['net_by_venue'].get('Binance.com',0):+,.0f}, Bybit {wave['net_by_venue'].get('Bybit',0):+,.0f}, Gate.io {wave['net_by_venue'].get('Gate.io',0):+,.0f} and the whale intermediary {wave['net_by_venue'].get('Unknown Whale I (active)',0):+,.0f}. Wave #2 therefore ran at roughly {100*wave['net_one_way']/otc['peak']['net']:.0f}% of the re-netted run #17 peak and has stopped. NEW RULE: net over the wave, treat weekly net one-way as an upper bound.

WHERE UPbit GETS ITS EGLD - ANSWERED, AND IT IS CIRCULAR. Run #20 flagged UPbit's flat balance while feeding the desks as evidence of an unobserved replenishment source worth ~20 queries. It was: the desks and their own feeders. UPbit's 30-day inbound is led by the Binance-to-desk feeder (70,611), the OTC Distribution Wallet itself (70,000), the UPbit OTC Desk (60,000), a second Binance feeder (50,005), a Bybit feeder (42,924) and the nonce-147 desk feeder (40,754). There is no external source to find - the hub recycles through UPbit, which is why cross-week netting matters so much.

BACKFILL COMPLETE (run #20 recommendation #7). Run #16: {f(otc['run16']['gross'])} gross, {otc['run16']['circ_pct']:.0f}% circular, {f(otc['run16']['net'])} one-way. Run #18: {f(otc['run18']['gross'])} gross, {otc['run18']['circ_pct']:.0f}% circular, {f(otc['run18']['net'])} one-way. The comparable net series is now {f(otc['run16']['net'])} / {f(otc['peak']['net'])} / {f(otc['run18']['net'])} / 61,435 / {f(otc['prev_net'])} / {f(otc['net_one_way'])} - a single peak in run #17 and nothing since above 40% of it. Run #18's 'collapse week', whose interpretation drove two runs of narrative, was {f(otc['run18']['net'])} one-way, which is roughly this week's level: the collapse was real but the level it collapsed TO is the model's normal.

THE BID IS DORMANT AGAIN. Zero. The Mega Whale absorber recorded no transactions at all ({bid['mega_change']:+.2f} EGLD of dust on {f(bid['mega_balance'])}), and the Coinbase Routing wallet that refilled it last week sat at {f(bid['cb_routing_balance'],1)} EGLD doing nothing. Run #20 pre-registered this exact outcome as the branch that would revive the dormancy finding, so it is revived: three of the last four weeks at zero, one week at 5,748. What is genuinely new is that this week the absence did not cost anything, because the offer disappeared too.

EXCHANGE FLOWS ARE UNINFORMATIVE THIS WEEK AND SHOULD BE STATED AS SUCH. Net {ex['net_total']:+,.0f} EGLD, the smallest in the series. Binance's {ex['ent_cur'].get('Binance',0)-ex['ent_prev'].get('Binance',0):+,.0f} is intra-entity (hot -127,064 -> custody +{f(cust['change'])} in one transfer), and roughly half of Bybit's {ex['ent_cur'].get('Bybit',0)-ex['ent_prev'].get('Bybit',0):+,.0f} fifth-week inflow is hub output rather than customer deposits. Six tracked addresses had no prior-week balance and were excluded from both sides of the delta per the run #18 rule.

WITHDRAWAL BREADTH, third measurement: {br['distinct_recipients_raw']} distinct non-exchange addresses received >1,000 EGLD out of tracked exchange wallets ({f(br['total_egld_raw'])} EGLD), of which {br['pipeline_share_pct']:.0f}% went into the OTC pipeline - down sharply from 84% in run #19 and consistent with the feed stopping. Ex-pipeline: {br['distinct_recipients_ex_pipeline']} addresses and {f(br['total_egld_ex_pipeline'])} EGLD, the largest ex-pipeline figure yet recorded, which is the closest thing to a genuine self-custody signal in this report.

'UNKNOWN WHALE I' RECLASSIFIED. With max_pages raised to 40 the 30-day trace completed without hitting the cap ({wi['in_txs']} in / {wi['out_txs']} out, {wi['in_counterparties']}/{wi['out_counterparties']} distinct counterparties, {f(wi['in_total'])}/{f(wi['out_total'])} EGLD). Hub infrastructure accounts for {wi['in_pipeline_pct']:.1f}% of inbound value, {wi['out_pipeline_pct']:.1f}% of outbound, {wi['combined_pipeline_pct']:.1f}% combined - clearing run #20's 60% threshold on the combined and inbound bases, missing it on outbound alone. Classified as OTC operator inventory with that caveat. Netting it out takes this week's one-way from {f(otc['net_one_way'])} to {f(otc['net_one_way']-wi['hub_net_this_week'])}; the more important consequence is that it is not a buyer, so it cannot be counted as demand.

Tier aggregates remain artifact-prone and are not narrated: mega {O['whale_tiers']['mega_whales']['net_change_egld']:+,.0f}, large {O['whale_tiers']['large_whales']['net_change_egld']:+,.0f}, mid {O['whale_tiers']['mid_whales']['net_change_egld']:+,.0f}."""

staking_analysis=f"""REWARD BEHAVIOR (new this run) is covered at the end of this section; the structural news is a correction.

THE DIRECT-NODE UNWIND DOES NOT EXIST. For three runs the model reported delegation TVL rising while total staked fell, attributed the ~215K difference to node operators leaving direct staking, and called it the largest unexplained flow it tracked. The residual is the wrong instrument. An unDelegate removes EGLD from a provider's `locked` figure immediately, but the EGLD stays inside the staking module for the 7-10 epoch unbonding period, so the residual (economics.staked minus summed provider locked) is a direct-node PLUS unbonding-pool measure. This week it flipped to {sk['raw_direct_residual']:+,.0f}, and a single wallet explains {f(UNW['total'])} of it: {f(UNW['legs'][0]['amount'])} unDelegated from p2p_org_ on 2026-08-15 and {f(UNW['legs'][1]['amount'])} from a second provider on 2026-08-14, both visible only as zero-value transactions with the amount encoded in the data field (the run #19 rule), both confirmed still unbonding via /accounts/{{addr}}/delegation with {UNW['legs'][1]['days_to_unbond']:.1f} and {UNW['legs'][0]['days_to_unbond']:.1f} days remaining. Corrected for in-flight unbonding, direct-node stake GREW {sk['corrected_direct']:+,.0f} this week. The prior three weeks' readings - residual falling while delegation rose - are equally consistent with earlier unbondings COMPLETING, and the model has no basis to claim node operators were exiting. The protocol Staking SC cannot be cross-checked directly: every transaction-query variant returns HTTP 400.

DELEGATION TVL {sk['deleg_tvl_wow']:+,.0f} TO {f(sk['total_locked'])} IS ALSO ONE WALLET. That same unwind is {UNW['share_of_delegation_decline_pct']:.0f}% of the decline; ex-it, delegation was {sk['deleg_tvl_wow']+UNW['total']:+,.0f} - flat. Per the run #16 single-entity rule this is a wallet event, not a market event. One provider did leave the active set entirely (locked 122,947 -> 0, seven users, and the second leg of the same wallet's unwind), the first >50K departure in tracking. Total staked itself ROSE {M['staked_chg']:+,} and the staked ratio {100*(M['sr']-M['sr_prev']):+.2f}pp to {M['sr']*100:.2f}%.

TWO PROVIDERS SET A 100% SERVICE FEE, AND RUN #20's HEADLINE IS WITHDRAWN. egldstakingprovider - the provider run #20 celebrated for cutting 24% -> 15% as 'the first competitive repricing in twenty runs' - moved to 100%, taking its delegator APR from 7.82% to zero. procryptostaking, the incumbent run #19 named as the one that had NOT cut, moved 20% -> 100%. Both verified against /providers, /providers?identity= and /providers/{{address}}; both still run 50 nodes; the owner wallets are different, so this is two unrelated operators making the same move in the same week rather than one entity. Both continued to bleed: {F1['locked_wow_egld']:+,.0f} EGLD and {F1['users_wow']:+d} delegators, {F2['locked_wow_egld']:+,.0f} and {F2['users_wow']:+d}. A 100% fee is a wind-down or a squeeze, not competition. The lesson for the model is narrower than it looks: fee arbitrage still describes where stake GOES, but a fee change is not evidence of a competitive market, and last week's reading inferred intent from a single parameter move.

The delegator response is worth its own sentence, because it is the strongest test participation inertia has faced. At a 100% fee a delegator earns literally nothing, and egldstakingprovider lost 26% of its book while its user count fell by just {abs(F1['users_wow'])} of ~1,124. Capital moved; people did not. If a zero-yield signal cannot move retail, nothing inside the normal 0-20% fee range will.

THE ROTATION UNDERNEATH IS UNCHANGED. The {sk['hi_apr_n']} providers at APR >= 8.8% took {sk['hi_apr_net']:+,.0f} EGLD net and zero-fee providers {sk['zero_fee_net']:+,.0f}. pi-staking extended its streak to a 10th consecutive week ({sk['pi_staking_wow']:+,.0f}, {sk['pi_staking_users_wow']:+d} delegators, 9.23% APR at 0% fee, now 21 nodes), with stakenest {sk['stakenest_wow']:+,.0f}, cslabsio {sk['cslabsio_wow']:+,.0f}, disruptivedigital {sk['disruptive_wow']:+,.0f} and vaporrepublic {sk['vapor_wow']:+,.0f} following the same pattern. Delegators {sk['churn']['total_delegators_current']:,} ({sk['churn']['delegators_added']:+}, a 9th flat week), {sk['churn']['providers_gaining_delegators']} providers gaining and {sk['churn']['providers_losing_delegators']} losing.

Concentration is unchanged and healthy: HHI {sk['hhi']:.5f} (vs {prev['staking_concentration']['hhi']:.5f}), top-5 {sk['top5']:.2f}%, top-10 {sk['top10']:.2f}%, {sk['n_providers']} active providers. The APR distribution is tightly clustered - {sk['buckets'][3]['provider_count']} providers in the 8-9% band holding {sk['buckets'][3]['total_locked_egld']/1e6:.2f}M EGLD, weighted-average APR {sk['apr_w']:.2f}% - with the new wrinkle that {sk['zero_apr_providers']} providers now sit at 0% APR holding {f(sk['zero_apr_locked'])} EGLD ({100*sk['zero_apr_locked']/sk['total_locked']:.1f}% of delegated stake), outside every bucket. For a delegator the standout deals are unchanged: mapleleafnetwork, stakenest and pi-staking at 9%+ APR on 0% fees.

REWARD BEHAVIOR: the function-level compound rate was {rw['compound_pct']:.2f}% ({rw['redelegate']} reDelegateRewards vs {rw['claims']} claimRewards across the top 8 providers), {rw['compound_pct']-rw['compound_prev']:+.2f}pp WoW and inside the 55-62% band the series has held for eleven runs. Of {rw['retail_n']} retail claims traced, {rw['retail_sold']} went to a labelled exchange and {rw['retail_held']} stayed in the claimant's wallet - the single most stable measurement in the model. The only selling cohort was institutional again: {rw['inst_n']} events, {f(rw['inst_val'])} EGLD, {100*rw['inst_sold_val']/rw['inst_val']:.0f}% of that value to an exchange. No sampled provider operator sold service-fee EGLD to an exchange in 30 days."""

token_analysis=f"""The token layer improved on the demand side and deteriorated on the dollar side.

xExchange volume was ${xx['total_volume_24h_usd']/1000:.1f}K ({xx['dex_vol_wow_pct']:+.1f}%) against pool TVL of ${xx['pool_tvl_usd']/1e6:.2f}M ({100*(xx['pool_tvl_usd']-xx['previous_pool_tvl_usd'])/xx['previous_pool_tvl_usd']:+.1f}%), so the TURNOVER RATIO rose a second consecutive week: {xx['previous_turnover_ratio_pct']:.2f}% -> {xx['turnover_ratio_pct']:.2f}% of pool TVL traded daily. The series is 4.06 / 2.14 / 2.24 / {xx['turnover_ratio_pct']:.2f} - the two-week halving has now recovered about three-quarters of the way back, and this is the first two-week improvement in any demand instrument since they were built. Run #19's ~4% threshold for calling the bid genuinely back is still unmet. Concentration {xx['top_pair_dominance_pct']:.1f}% in WEGLD/USDC.

MEX's OUTPERFORMANCE IS NOT A PRICING ARTIFACT - and this run had to check because the model had asserted the opposite twice. MEX {xx['mex_price_change_wow_pct']:+.2f}% WoW to ${xx['mex_price_usd']:.3e} (mcap ${xx['mex_market_cap_usd']/1e6:.2f}M) against EGLD's {pc:+.2f}%, a fourth consecutive week at or above the native asset. Runs #19 and #20 both attributed this to stale pricing in illiquid pairs. Measured: the MEX/WEGLD pair holds ${xx['mex_pair_depth']['tvl_usd']:,.0f} of pool TVL, which is {xx['mex_pair_depth']['share_of_pool_tvl_pct']:.1f}% of ALL xExchange depth and the #{xx['mex_pair_depth']['depth_rank']} deepest pool on the venue, and it traded {xx['mex_pair_depth']['trades_24h']} times in the last 24 hours on ${xx['mex_pair_depth']['volume_24h_usd']:,.0f} of volume. Thin in volume, but priced. The explanation is withdrawn and replaced by an open question: why the DEX token leads the chain's native asset through a distribution episode.

BRIDGED USDT FELL {df['usdt_supply_wow']:+.2f}% - {f(df['usdt_supply_prev']-df['usdt_supply'])} tokens, {f(df['usdt_supply_prev'])} -> {f(df['usdt_supply'])} - the largest single-week stablecoin contraction in tracking against a prior worst of -3.7% in run #14. USDC fell {df['usdc_supply_wow']:+.2f}% to {f(df['usdc_supply'])}. WEGLD supply was flat ({df['wegld_supply_wow']:+.2f}%), so EGLD is neither being wrapped nor unwrapped at any scale. Nine consecutive runs without a stablecoin inflow week, and this the sharpest exit of them: it is the one instrument this week that contradicts the price action.

Holder counts declined marginally across the top 10 for a 21st consecutive week - the airdrop-decay baseline, not a signal.

Newly-issued: the ESDT system-SC scan surfaced exactly one issuance, and it is worth naming as a warning rather than a launch - `BTC-8549df`, named "Bitcoin", with 3 holders and 23 transactions, filtered by the run #15 quality bar (>10 holders, >5 transactions). Qualifying new-token formation is now zero for a fifth consecutive week, and the only thing being minted is a ticker impersonating an existing asset. For a chain whose thesis rests on application-layer growth this remains the most durable problem in the report."""

defi_analysis=f"""DeFi did nothing this week, and after four weeks of de-risking that is itself the finding.

USH supply moved {df['ush_supply_wow']:+.3f}% to {f(df['ush_supply'])} - a second consecutive week inside the noise band, confirming the run #19-#20 de-leveraging is complete. The informative half is what did NOT happen: price rose {pc:+.2f}% and CDP borrowers did not re-open positions. Per the run #16 mirror rule, a mint above +5% is the signal that leverage is returning; two flat weeks through a rally says the borrowers who cut in July are not coming back at this price.

HATOM LENDING's three-week EGLD-denominated growth streak ENDED: {df['hatom_lending_egld_wow_pct']:+.2f}% to {df['hatom_lending_egld']/1000:.0f}K EGLD (${df['hatom_lending_usd']/1e6:.2f}M, {100*(df['hatom_lending_usd']-df['prev_hl_usd'])/df['prev_hl_usd']:+.1f}% USD). METHODOLOGICAL NOTE, enforced since run #20: the bilateral inverse rule is NOT evaluable at a {pc:+.2f}% price move - the |5%| guardrail is not met, the mechanical ratio of {df['inverse_ratio_mechanical']:.2f} is a small-denominator artifact, and the confirmation count stays at seven. What is reportable is that the sign is at least consistent (deposits shrank in EGLD terms as price rose, the profit-taking direction), and that the cohort which had been the only consistent adder on the chain for three weeks stopped adding.

XOXNO's LSD REDEMPTION IS TRACED AND BENIGN (run #20 recommendation #3, the highest-value open DeFi question). XEGLD supply fell {df['xegld_supply_wow']:+.2f}% to {f(df['xegld_supply'])}, decelerating from -2.23%. The contract itself has ZERO outbound value transactions - it settles via smart-contract results, the pattern documented in runs #15 and #19 - so the trace ran through the callers: {O['xegld_trace']['fn_counts']['unDelegate']} unDelegate, {O['xegld_trace']['fn_counts']['unDelegatePending']} unDelegatePending, {O['xegld_trace']['fn_counts']['withdraw']} withdraw and {O['xegld_trace']['fn_counts']['withdrawPending']} withdrawPending calls from {O['xegld_trace']['callers']} distinct wallets in the window. Their onward flows are small and heterogeneous - 80 to 600 EGLD each, {f(O['xegld_trace']['delegation_egld'])} EGLD delegated into native staking contracts, the remainder to unlabeled wallets and one game contract, and ZERO EGLD to any labelled exchange. Per the pre-commitment that is the constructive/idiosyncratic branch: retail-scale rotation out of the LSD, partly into native delegation, not an exit.

HATOM LIQUID STAKING is the most inert instrument tracked: SEGLD supply {df['segld_supply_wow']:+.3f}% (a fourth flat week), SWTAO {df['swtao_supply_wow']:+.2f}%, ${df['hatom_lsd_usd']/1e6:.2f}M ({100*(df['hatom_lsd_usd']-df['prev_hlsd_usd'])/df['prev_hlsd_usd']:+.1f}% USD). Neither the July drawdown nor this week's rally has moved it.

In USD terms: Hatom Lending ${df['hatom_lending_usd']/1e6:.2f}M, Hatom LSD ${df['hatom_lsd_usd']/1e6:.2f}M, XOXNO LSD ${df['xoxno_lsd_usd']/1e6:.2f}M, USH ${df['ush_usd']/1000:.0f}K. With price up 3% the USD figures flatter the EGLD-denominated moves, so the run #13 price-artifact caveat applies in the opposite direction from usual this week.

Routing activity: XOXNO Aggregator {tr.get('XOXNO Aggregator'):,} daily transfers (down from last week's spike), OneDex {tr.get('OneDex Swap'):,}, JEXchange fees wallet {tr.get('JEXchange Fees'):,}. Routing fell while DEX turnover rose, so the two no longer corroborate each other - worth watching rather than interpreting.

The dataApi price feed was clean for a 7th consecutive run: zero re-fetch retries across all four dataApi-class tokens (SEGLD, SWTAO, USH, XEGLD)."""

json.dump({"executive_summary":executive_summary,"network_health":network_health,
           "exchange_flows":exchange_flows,"protocol_breakdown":protocol_breakdown,
           "protocols":protocols,"whale_analysis":whale_analysis,
           "staking_analysis":staking_analysis,"token_analysis":token_analysis,
           "defi_analysis":defi_analysis}, open("/tmp/run21w/part4.json","w"), indent=1)
print("STAGE 4 OK exec_summary",len(executive_summary))
