#!/usr/bin/env python3
"""Run #23 stage 4: anomalies, trend indicators, watch list -> /tmp/run23w/part3.json"""
import json
REPO="/Users/ls/Documents/MultiversX/projects/onchain-quant-agent"
RD="2026-08-31"
O=json.load(open("/tmp/run23w/derived.json"))
D=json.load(open(f"{REPO}/data/collected/{RD}.json"))
prev=json.load(open(f"{REPO}/data/previous.json"))
beh=json.load(open(f"{REPO}/data/collected/delegator_behavior_{RD}.json"))
M=O["macro"]; otc=O["otc"]; wave=otc["wave"]; ex=O["exch"]
cust=O["custody"]; bid=O["bid"]; br=O["breadth"]; sk=O["staking"]; tk=O["tokens"]
xx=O["xexchange"]; df=O["defi"]; z=O["z"]; ub=O["unbond"]; absb=O["absorbers"]; p2p=O["p2p"]
price=M["price"]; pc=M["price_chg"]; econ=D["economics"]
cvc=beh["aggregates"]["compound_vs_claim_at_function_level"]
def f(x,d=0):
    try: return f"{x:,.{d}f}"
    except: return str(x)
def zz(k): return z[k].get("z")
R={}

R["anomalies"]=[
 {"metric":"otc_desk_inventory_egld","current_value":otc["desk_bal"],
  "previous_value":otc["prev_desk"],"method":"rule_based","severity":"critical",
  "change_pct":100*otc["desk_delta"]/otc["prev_desk"],
  "description":f"Combined OTC desk inventory {f(otc['desk_bal'])} EGLD, +{f(otc['desk_delta'])} ({100*otc['desk_delta']/otc['prev_desk']:+.0f}%) - 2.4x last week's record and by a wide margin the largest staged supply position in tracking. The comparison that matters: the run #17 peak wave DELIVERED 409,680 one-way from a starting inventory of 335,430; the desks now hold {f(otc['desk_bal'])} having ALREADY delivered {f(otc['net_one_way'])} this week, with the feed still running. This is the single most decision-relevant number in the report."},
 {"metric":"otc_pipeline_upbit_tranche_egld","current_value":otc["upbit_feed"],
  "previous_value":otc["prev_upbit_feed"],"method":"rule_based","severity":"critical",
  "change_pct":100*(otc["upbit_feed"]-otc["prev_upbit_feed"])/otc["prev_upbit_feed"],
  "description":f"UPbit fed {f(otc['upbit_feed'])} EGLD into the desks against 297,000 last week and 14,000 the week before. That is 3x run #21's escalation threshold of ~150,000 and makes the tranche series 14,000 / 297,000 / {f(otc['upbit_feed'])} - an escalating programme, not episodic reloads. UPbit is the sole net SOURCE of the whole pipeline at {f(otc['net_by_venue'].get('UPbit',0))} this week and {f(wave['net_by_venue'].get('UPbit',0))} over the Aug 17-31 wave."},
 {"metric":"provider_deregistration_backfill","current_value":3,"previous_value":1,
  "method":"rule_based","severity":"critical",
  "description":f"THREE operator deregistrations exist in the archive, not one. Applying run #22's own signature (locked == 0 with numNodes > 0) to the stored snapshots: ledgerbyfigment went 170,808 EGLD -> 0 between the 2026-06-08 and 2026-06-15 snapshots (the run #13 window) with 7 nodes and 3,961 delegators, and stakedinc has been zero-locked with 10 nodes and ~639 users across the entire stored history. Neither was ever reported. Run #22's 'first operator deregistration in tracking' is withdrawn. p2p_org_ additionally COMPLETED its exit this week - removeNodes x{p2p['function_counts'].get('removeNodes',0)} plus unBondNodes, numNodes 50 -> 0 - which also breaks the detection signature, since a fully exited operator has no nodes left to match on."},
 {"metric":"egld_price_usd","current_value":price,"previous_value":M["prev_price"],
  "method":"z_score","severity":"medium",
  "average_value":z["price"]["mean"],"stddev":z["price"]["stddev"],"z_score":zz("price"),
  "change_pct":pc,
  "description":f"EGLD ${price:.2f}, {pc:+.2f}%, z={zz('price'):+.2f}sigma. The rule-based cross-check is the finding, not the z: BTC {M['btc_wow']:+.2f}% and ETH {M['eth_wow']:+.2f}% BOTH FELL, so this is an EGLD-specific move under the run #16 decoupling rule - the opposite of last week, when +30.43% landed between the majors and carried no EGLD-specific component. The run #16 caveat also applies: three consecutive up-weeks have pulled the baseline mean up, so the absolute z understates the break."},
 {"metric":"binance_staking_custody_egld","current_value":cust["balance"],
  "previous_value":cust["previous"],"method":"z_score","severity":"high",
  "average_value":z["custody"]["mean"],"stddev":z["custody"]["stddev"],"z_score":zz("custody"),
  "change_pct":100*cust["delta"]/cust["previous"],
  "description":f"Binance Staking custody {f(cust['delta'])} to {f(cust['balance'])}, z={zz('custody'):+.2f}sigma - a second consecutive drawdown, -497K over two weeks, and the lowest custody balance since the position was first flagged in run #9. The mechanics are fully traced this week: custody sent {f(cust['custody_out_this_window'])} to the Binance.com hot wallet, the hot wallet forwarded {f(cust['hot_to_desk_total'])} into the OTC desks through two previously identified feeders plus one direct transfer, and returned {f(cust['hot_to_custody_egld'])} to custody. The custody watch and the pipeline watch are one instrument from here."},
 {"metric":"unbonding_queue_undelegated_egld_7d","current_value":sk["undelegated_week"],
  "previous_value":70498,"method":"rule_based","severity":"high",
  "change_pct":100*(sk["undelegated_week"]-70498)/70498,
  "description":f"{f(sk['undelegated_week'])} EGLD unDelegated by {sk['undelegate_callers']} distinct wallets across all {sk['providers_scanned']} provider contracts - 2.1x run #22's 70,498, which was measured across ten providers only. The jump is mostly METHOD, not behaviour: the first full-set scan shows the partial scan was missing more than half the queue. Measured pending unbonding {f(sk['pool_total'])} EGLD. Treat the {f(sk['undelegated_week'])} as the first comparable point in a new series, not as a 2x increase in unbonding."},
 {"metric":"absorber_scan_retained_share_pct",
  "current_value":100*absb["total_retained"]/absb["total_received"] if absb["total_received"] else 0,
  "previous_value":None,"method":"rule_based","severity":"high",
  "description":f"Run #22's proposed repair of the identifiable-bid instrument returns a decisive negative. All {absb['scanned']} of the desks' outbound terminals were scanned for wallets that RETAIN what they receive: {f(absb['total_received'])} EGLD passed through them and {f(absb['total_retained'])} ({100*absb['total_retained']/absb['total_received']:.1f}%) stayed. Every terminal is a zero-balance, high-nonce pass-through router. There are no absorbers on the outbound side of this pipeline to discover, so the instrument is RETIRED rather than repaired. The Mega Whale proxy read exactly zero for a third consecutive week (balance {f(bid['mega_bal'],4)} unchanged to four decimals, zero transactions) and in four of the last five."},
 {"metric":"dex_volume_egld_24h","current_value":bid["dexvol_egld"],
  "previous_value":bid["prev_dexvol_egld"],"method":"rule_based","severity":"medium",
  "change_pct":100*(bid["dexvol_egld"]-bid["prev_dexvol_egld"])/bid["prev_dexvol_egld"],
  "description":f"Run #22 asked for DEX volume in EGLD terms so the turnover signal could be separated from the price move, and the separation matters: turnover held at {bid['turnover']:.2f}% (above its ~5% regime branch) while EGLD-denominated volume FELL from {f(bid['prev_dexvol_egld'])} to {f(bid['dexvol_egld'])} EGLD/day ({100*(bid['dexvol_egld']-bid['prev_dexvol_egld'])/bid['prev_dexvol_egld']:+.1f}%) and EGLD-denominated pool depth fell {100*(bid['pooltvl_egld']-bid['prev_pooltvl_egld'])/bid['prev_pooltvl_egld']:+.1f}%. The ratio held because both sides scaled with a +6.4% price. The venue processed slightly LESS EGLD than last week."},
 {"metric":"reward_compound_pct","current_value":cvc["compound_pct_of_reward_decisions"],
  "previous_value":57.03,"method":"z_score","severity":"medium",
  "average_value":z["compound"]["mean"],"stddev":z["compound"]["stddev"],"z_score":zz("compound"),
  "description":f"Compound rate {cvc['compound_pct_of_reward_decisions']:.2f}% ({cvc['redelegate_count']} redelegate vs {cvc['claim_count']} claim), z={zz('compound'):+.2f}sigma - a fourth consecutive decline and the lowest of ten readings. The pre-committed test could not resolve: its branches were 'below 56%' and 'above 59%' and the reading landed between them. Read on the trend instead: four declines spanning a flat week, a +30% week and a +6% week is not price-following, it is a slow drift toward taking yield in cash. The institutional tier sold 3 of 6 claims for a second consecutive week; retail sold nothing for a tenth run."},
 {"metric":"withdrawal_breadth_ex_pipeline_egld","current_value":br["ex_egld"],
  "previous_value":133520.83666306452,"method":"rule_based","severity":"medium",
  "change_pct":100*(br["ex_egld"]-133520.83666306452)/133520.83666306452,
  "description":f"{br['ex_n']} distinct non-exchange addresses took {f(br['ex_egld'])} EGLD off exchanges outside the pipeline, against 21 recipients and 133,521 last week, with the pipeline share of exchange outflow value falling from 88.3% to {br['pipeline_share']:.1f}%. This is the only unambiguously constructive instrument in the report and it is at its best reading since the measure was built. It is also the first week with a full 7-day scan and ZERO page-cap terminations, after the hot-wallet page budget was raised on run #22's recommendation - so unlike previous weeks the raw figure of {f(br['raw_egld'])} EGLD is not a lower bound."},
 {"metric":"stablecoin_supply_usdc","current_value":tk["stable"]["USDC-c76f1f"]["supply"],
  "previous_value":tk["stable"]["USDC-c76f1f"]["prev"],"method":"rule_based","severity":"medium",
  "change_pct":tk["stable"]["USDC-c76f1f"]["pct"],
  "description":f"USDC supply {tk['stable']['USDC-c76f1f']['pct']:+.2f}% to {f(tk['stable']['USDC-c76f1f']['supply'])} ({f(abs(tk['stable']['USDC-c76f1f']['supply']-tk['stable']['USDC-c76f1f']['prev']))} tokens redeemed), well past the 0.1% stablecoin threshold, alongside USDT {tk['stable']['USDT-f8c08c']['pct']:+.2f}% to {f(tk['stable']['USDT-f8c08c']['supply'])}. About $77K of on-chain dollars left in a week when EGLD rose 6.4% - dollars exiting into strength, the same direction as every other holding-side instrument."},
 {"metric":"ush_supply","current_value":tk["lsd"]["USH-111e09"]["supply"],
  "previous_value":tk["lsd"]["USH-111e09"]["prev"],"method":"rule_based","severity":"medium",
  "change_pct":tk["lsd"]["USH-111e09"]["pct"],
  "description":f"USH supply {tk['lsd']['USH-111e09']['pct']:+.2f}% ({f(abs(tk['lsd']['USH-111e09']['supply']-tk['lsd']['USH-111e09']['prev']))} tokens burned) to {f(tk['lsd']['USH-111e09']['supply'])} - a SECOND consecutive burn into a rising price, cumulative -2.4%. One burn into a rally was an anomaly against the run #11/#16 framing; two makes it a behaviour. CDP borrowers are retiring debt as collateral appreciates, the mirror of run #16 where a +16% week produced a +6.49% MINT."},
 {"metric":"hatom_lending_inverse_response_ratio","current_value":df["inverse_ratio"],
  "previous_value":0.28,"method":"rule_based","severity":"low",
  "description":f"BILATERAL INVERSE RULE, fourth up-week confirmation: price {pc:+.2f}%, Hatom Lending EGLD-denominated TVL {df['hatom_lending_egld_pct']:+.2f}%, response ratio {df['inverse_ratio']:.2f}. Run #22 registered that a SECOND consecutive sub-0.30 reading would mean the deposit base was exhausted and the rule should be retired. It did not come - the up-week series is 0.49 / 0.72 / 0.28 / {df['inverse_ratio']:.2f}, so the 0.28 is reclassified as one weak response to an unusually large price move rather than depletion. The rule survives."},
 {"metric":"exchange_net_flow_egld","current_value":ex["net"],
  "previous_value":-33937,"method":"z_score","severity":"low",
  "average_value":z["exflow"]["mean"],"stddev":z["exflow"]["stddev"],"z_score":zz("exflow"),
  "description":f"Net exchange flow {ex['net']:+,.0f} EGLD, z={zz('exflow'):+.2f}sigma. Per the run #15 rule it must be decomposed before it is labelled: UPbit's {next((w['change_egld'] for w in ex['per_wallet'] if 'UPbit' in w['exchange']),0):+,.0f} is desk loading and Binance's {next((e2['net_flow_egld'] for e2 in ex['entity'] if e2['entity']=='Binance'),0):+,.0f} is internal plumbing. Ex those two the complex took a mild INFLOW of {ex['net']-next((w['change_egld'] for w in ex['per_wallet'] if 'UPbit' in w['exchange']),0)-next((e2['net_flow_egld'] for e2 in ex['entity'] if e2['entity']=='Binance'),0):+,.0f} led by Bybit and Bitget - both hub destinations, so even that is pipeline output rather than independent customer behaviour."},
 {"metric":"otc_pipeline_throughput_egld_7d","current_value":otc["gross_out"],
  "previous_value":767206,"method":"z_score","severity":"low",
  "average_value":z["otc"]["mean"],"stddev":z["otc"]["stddev"],"z_score":zz("otc"),
  "description":f"Gross desk throughput {f(otc['gross_out'])} EGLD out against {f(otc['gross_in'])} in, z={zz('otc'):+.2f}sigma - unremarkable against a baseline that already contains the 1.28M run #17 peak, which is why the gross figure is reported at low severity and the inventory and tranche numbers carry the finding. Net one-way {f(otc['net_one_way'])} at {otc['circ_pct']:.0f}% circularity - just BELOW the historical 63-80% band, which run #21 established as the diagnostic tell that a wave straddles a week boundary. It does; see the wave-window netting."},
 {"metric":"total_delegators","current_value":sk["users"],"previous_value":sk["prev_users"],
  "method":"rule_based","severity":"low",
  "change_pct":100*sk["users_delta"]/sk["prev_users"],
  "description":f"Delegator count {sk['users_delta']:+,} to {f(sk['users'])} ({100*sk['users_delta']/sk['prev_users']:+.3f}%). Reported rule_based rather than by z-score because the baseline's standard deviation is tiny relative to the base and produces the degenerate sigma the run #9 guard exists to suppress. Unlike last week there is no deregistration artifact to net out, so this is a clean reading and it confirms the run #18 base rate: the delegator base does not move, in either direction, at any price."},
]

R["trend_indicators"]={
 "accelerating_exchange_outflows":[
  {"exchange":"UPbit","trend":"down","cumulative_change_pct":-20.1,"weeks_in_trend":2,
   "interpretation":f"UPbit {next((w['change_egld'] for w in ex['per_wallet'] if 'UPbit' in w['exchange']),0):+,.0f} for a second consecutive week while sending {f(otc['upbit_feed'])} to its own OTC desk. Per the run #16 rule this is the LOADING leg of a distribution programme, not customer withdrawal. Over the two weeks it has fed the desks 757,000 EGLD and its balance has fallen ~280,000 - the difference is inventory cycling back from the desks."},
  {"exchange":"Binance","trend":"down","cumulative_change_pct":-11.3,"weeks_in_trend":2,
   "interpretation":f"Binance Staking custody {f(cust['delta'])} on top of last week's -300,000, and this week the destination is traced all the way through: hot wallet -> {f(cust['hot_to_desk_total'])} into the OTC desks via two named feeders. Two channels that were tracked separately for fourteen runs are one programme."},
  {"exchange":"Bybit","trend":"up","cumulative_change_pct":17.4,"weeks_in_trend":3,
   "interpretation":f"+{f(next((e2['net_flow_egld'] for e2 in ex['entity'] if e2['entity']=='Bybit'),0))} for a third consecutive build. Bybit is simultaneously the second-largest net receiver from the hub (+{f(otc['net_by_venue'].get('Bybit',0))}) AND a feeder into it ({f(otc['in_by_venue'].get('Bybit',0))} in) - it sits on both sides, which is what the circularity measure exists to separate."},
  {"exchange":"Coinbase","trend":"down","cumulative_change_pct":-45.8,"weeks_in_trend":2,
   "interpretation":f"{next((e2['net_flow_egld'] for e2 in ex['entity'] if e2['entity']=='Coinbase'),0):+,.0f} across {next((e2['wallets_count'] for e2 in ex['entity'] if e2['entity']=='Coinbase'),0)} wallets, a second consecutive fall. Resolved per the run #17 migration rule: Coinbase Custody 2 sent 40,000 and Coinbase (secondary) 18,108 to Unknown Whale B, which holds the lot. A withdrawal to a holder, not distribution."},
  {"exchange":"Bitget","trend":"up","cumulative_change_pct":21.3,"weeks_in_trend":1,
   "interpretation":f"+{f(next((e2['net_flow_egld'] for e2 in ex['entity'] if e2['entity']=='Bitget'),0))} ({next((e2['pct'] for e2 in ex['entity'] if e2['entity']=='Bitget'),0):+.1f}%), the largest proportional build of the week, and Bitget appears as an OTC hub destination for the first time (+{f(otc['net_by_venue'].get('Bitget',0))} two-hop-resolved). That takes the delivery-side venue count to five and is a genuine widening of the distribution surface rather than a rotation among the existing four."}],
 "validator_movements":{
  "providers_joining":0,"providers_leaving":0,"net_provider_change":0,
  "notable_joiners":[],
  "notable_leavers":[
    {"identity":"ledgerbyfigment","name":"ledgerbyfigment (BACKFILLED - deregistered in the run #13 window, never reported)",
     "previous_locked_egld":170808.0},
    {"identity":"stakedinc","name":"stakedinc (BACKFILLED - zero-locked across the entire stored history)",
     "previous_locked_egld":0.0}]},
 "token_supply_events":[
  {"identifier":"USDC-c76f1f","name":"WrappedUSDC","event":"burn",
   "supply_previous":str(int(tk["stable"]["USDC-c76f1f"]["prev"])),
   "supply_current":str(int(tk["stable"]["USDC-c76f1f"]["supply"])),
   "change_pct":tk["stable"]["USDC-c76f1f"]["pct"],
   "description":f"{f(abs(tk['stable']['USDC-c76f1f']['supply']-tk['stable']['USDC-c76f1f']['prev']))} USDC redeemed ({tk['stable']['USDC-c76f1f']['pct']:+.2f}%), well past the 0.1% stablecoin threshold. Together with USDT's {tk['stable']['USDT-f8c08c']['pct']:+.2f}% that is ~$77K of on-chain dollars leaving during a +6.4% price week."},
  {"identifier":"USDT-f8c08c","name":"WrappedUSDT","event":"burn",
   "supply_previous":str(int(tk["stable"]["USDT-f8c08c"]["prev"])),
   "supply_current":str(int(tk["stable"]["USDT-f8c08c"]["supply"])),
   "change_pct":tk["stable"]["USDT-f8c08c"]["pct"],
   "description":f"USDT {tk['stable']['USDT-f8c08c']['pct']:+.2f}% to {f(tk['stable']['USDT-f8c08c']['supply'])}, resuming the contraction that run #21 flagged and run #22 read as resolved. Two of the last three weeks negative on a base under 600K."},
  {"identifier":"USH-111e09","name":"Hatom USH","event":"burn",
   "supply_previous":str(int(tk["lsd"]["USH-111e09"]["prev"])),
   "supply_current":str(int(tk["lsd"]["USH-111e09"]["supply"])),
   "change_pct":tk["lsd"]["USH-111e09"]["pct"],
   "description":f"{f(abs(tk['lsd']['USH-111e09']['supply']-tk['lsd']['USH-111e09']['prev']))} USH burned ({tk['lsd']['USH-111e09']['pct']:+.2f}%), a second consecutive burn into a rising price. CDP borrowers retiring debt as collateral appreciates - a behaviour, not an anomaly, now that it has repeated."},
  {"identifier":"MEX-455c57","name":"MEX","event":"burn",
   "supply_previous":str(int(tk["mex_prev_supply"])),
   "supply_current":str(int(tk["mex_supply"])),
   "change_pct":100*(tk["mex_supply"]-tk["mex_prev_supply"])/tk["mex_prev_supply"],
   "description":f"MEX supply {100*(tk['mex_supply']-tk['mex_prev_supply'])/tk['mex_prev_supply']:+.3f}%, far inside the 1% threshold the mechanism test required. Combined with MEX/WEGLD pool depth moving {xx['mex_pair_depth']['tvl_egld_wow_pct']:+.2f}% in EGLD terms, neither branch of the mechanism test fires and the outperformance is closed as unexplained flow."}],
 "consecutive_streaks":[
  {"metric":"otc_desk_inventory_egld","direction":"up","weeks":2,
   "cumulative_change_pct":338.9,
   "interpretation":f"60,565 -> 109,857 -> {f(otc['desk_bal'])}. Two consecutive reloads to successive records while ALSO delivering {f(otc['net_one_way'])} one-way this week. The pipeline is accumulating faster than it distributes, which has not happened before in tracking."},
  {"metric":"reward_compound_pct","direction":"down","weeks":4,
   "cumulative_change_pct":100*(cvc["compound_pct_of_reward_decisions"]-62.25)/62.25,
   "interpretation":f"62.25 -> 59.54 -> 59.07 -> 57.03 -> {cvc['compound_pct_of_reward_decisions']:.2f}%. Four consecutive declines spanning a flat week, a +30% week and a +6% week. Because the sign is the same across opposite price regimes, this is not a price-following series - it is a slow drift toward monetising yield."},
  {"metric":"identifiable_bid_absorbed_egld_7d","direction":"flat","weeks":3,
   "cumulative_change_pct":0.0,
   "interpretation":"Zero for a third straight week and in four of the last five. With the absorber scan returning no candidates anywhere on the desks' outbound side, the instrument is retired rather than re-reported."},
  {"metric":"lsd_supply_all","direction":"flat","weeks":6,
   "cumulative_change_pct":0.0,
   "interpretation":"SEGLD, XEGLD and SWTAO have all sat inside the noise band on the supply basis for six weeks, through a cumulative ~+39% price move. Nobody has converted this rally into a yield-bearing on-chain position at any measurable scale."},
  {"metric":"total_delegators","direction":"flat","weeks":11,
   "cumulative_change_pct":-0.9,
   "interpretation":f"{sk['users_delta']:+,} this week to {f(sk['users'])}, and this time with no deregistration artifact to net out. Run #18 promoted the flat base to a background assumption at six weeks; at eleven, with two providers now proven to hold their books at 0% APR for a quarter, it is better described as a structural property of this delegation market than as a weekly observation."},
  {"metric":"provider_operator_fee_selling","direction":"flat","weeks":11,
   "cumulative_change_pct":0.0,
   "interpretation":"Eleven consecutive runs with zero exchange destinations from any sampled provider-operator wallet. A base rate; only a break would be newsworthy."},
  {"metric":"newly_issued_quality","direction":"flat","weeks":7,
   "cumulative_change_pct":0.0,
   "interpretation":f"Seven consecutive weeks with no token issuance clearing the >10-holder / >5-transaction bar. This week's {len(tk['newly'])} all have exactly 1 holder. Primary issuance on this chain is effectively dormant."}],
 "regime_shifts":[
  {"metric":"otc_desk_inventory_egld","before_value":109857.0,"after_value":otc["desk_bal"],
   "description":f"Desk inventory stepped from a 60-110K band to {f(otc['desk_bal'])} while simultaneously delivering {f(otc['net_one_way'])} one-way. Flagged as a CANDIDATE regime shift: the methodology requires the new level to hold two weeks before promotion, and the obvious alternative is a single large staging event that drains next week. Pre-committed thresholds registered below."},
  {"metric":"binance_pipeline_participation","before_value":0.0,
   "after_value":cust["hot_to_desk_total"],
   "description":f"Binance moved from being the pipeline's ultimate ORIGIN (run #10, via a source-funder chain) to feeding the desks directly: {f(cust['hot_to_desk_total'])} EGLD from the Binance.com hot wallet into two named OTC feeders and one desk this week, funded by a {f(cust['custody_out_this_window'])} custody drawdown. For fourteen runs the custody watch and the pipeline watch were separate instruments; they are now one."},
  {"metric":"operator_deregistration_count","before_value":1,"after_value":3,
   "description":"Not a shift in the world but in what the model can see. The deregistration signature invented in run #22 was applied backwards this run and found two prior cases, the larger of which (ledgerbyfigment, 170,808 EGLD, 3,961 delegators) went unreported for ten runs. Any claim of the form 'first X in tracking' should now be checked against the archive with the detector that found it, in the same run."}]}

R["watch_list"]=[
 {"item":f"OTC DESK INVENTORY AT A RECORD {f(otc['desk_bal'])} EGLD - the drain leg of wave #3 is still ahead",
  "weeks_on_list":23,
  "reason":f"The desks delivered {f(otc['net_one_way'])} one-way this week AND ended +{f(otc['desk_delta'])} at {f(otc['desk_bal'])}, 2.4x last week's record. UPbit's tranche series is 14,000 / 297,000 / {f(otc['upbit_feed'])}. Destinations two hops out: Binance.com +{f(otc['net_by_venue'].get('Binance.com',0))}, Bybit +{f(otc['net_by_venue'].get('Bybit',0))}, Gate.io +{f(otc['net_by_venue'].get('Gate.io',0))}, Bitget +{f(otc['net_by_venue'].get('Bitget',0))} (new). PRE-COMMITTED: desks draining below ~120,000 next week = the overhang is being delivered and this is the largest single distribution wave in tracking; inventory holding above ~220,000 with the feed continuing = staging is still running and the delivery is ahead of us, not behind."},
 {"item":"BINANCE CUSTODY -> HOT -> OTC DESKS is one programme; custody down 497K in two weeks",
  "weeks_on_list":17,
  "reason":f"Custody {f(cust['balance'])} ({f(cust['delta'])} this week, -497K over two). The hot wallet forwarded {f(cust['hot_to_desk_total'])} into the desks through the run #19 and run #20 feeders plus one direct transfer, and returned {f(cust['hot_to_custody_egld'])} to custody. The balance-based branch registered in run #22 could not see this because custody refilled the hot wallet faster than it spent. PRE-COMMITTED, now specified on FLOW not balance: Binance hot sending more than ~50,000 to desk feeders again next week = a standing funding programme and the custody drawdown should be read as scheduled supply; nothing above ~10,000 = this week was a one-off routing and the two watches separate again."},
 {"item":"THE VALIDATOR SET's DISTRESSED TAIL - three deregistrations, two of them found retrospectively",
  "weeks_on_list":2,
  "reason":f"ledgerbyfigment (7 nodes, 3,883 users, zero-locked since the run #13 window, 170,808 EGLD at the time), stakedinc (10 nodes, 637 users, zero-locked across the whole archive), p2p_org_ (exit COMPLETED this week, numNodes 50 -> 0, 1,244 users still attached). Plus two providers at serviceFee 1.0 / APR 0 holding {f(sk['zero_apr_locked'])} EGLD between the five zero-APR contracts. PRE-COMMITTED: a FOURTH provider hitting locked == 0 with users attached within four weeks = operator attrition is a trend and the delegation market is losing its long tail; none = the three are idiosyncratic business decisions."},
 {"item":"PARTICIPATION INERTIA - now an eleven-week measurement, not a weekly observation",
  "weeks_on_list":3,
  "reason":f"ledgerbyfigment has paid nothing for eleven weeks and lost 78 of 3,961 delegators (-2.0%); stakedinc has lost 2 of 639 across the archive; p2p_org_ produced {p2p['function_counts'].get('unDelegate',0)} unDelegate calls from 1,244 users this week against {p2p['function_counts'].get('reDelegateRewards',0)} reDelegateRewards on a dead contract. Meanwhile the 100%-fee providers' books fell {100*next(m['delta'] for m in sk['moves'] if m['identity']=='egldstakingprovider')/79639:.1f}% and {100*next(m['delta'] for m in sk['moves'] if m['identity']=='procryptostaking')/141804:.1f}% with users down {next(m['users_delta'] for m in sk['moves'] if m['identity']=='egldstakingprovider'):+d} and {next(m['users_delta'] for m in sk['moves'] if m['identity']=='procryptostaking'):+d}. Capital responds to price; people do not. GRADUATING to a background assumption per the run #18 rule - only a break is reportable from here."},
 {"item":"DEX TURNOVER - the ratio held, the EGLD throughput did not",
  "weeks_on_list":5,
  "reason":f"Turnover {bid['turnover']:.2f}% vs {bid['prev_turnover']:.2f}%, above the ~5% regime branch, so the pre-committed test fires constructively. But volume in EGLD terms fell {100*(bid['dexvol_egld']-bid['prev_dexvol_egld'])/bid['prev_dexvol_egld']:+.1f}% to {f(bid['dexvol_egld'])} EGLD/day and pool depth {100*(bid['pooltvl_egld']-bid['prev_pooltvl_egld'])/bid['prev_pooltvl_egld']:+.1f}%. PRE-COMMITTED: EGLD-denominated volume above ~70,000/day next week = a genuine demand regime and the constructive reading stands on its own terms; below ~60,000 = the USD turnover ratio is tracking price and should be reported in EGLD from here."},
 {"item":"WITHDRAWAL BREADTH EX-PIPELINE - best reading since the instrument was built",
  "weeks_on_list":5,
  "reason":f"{br['ex_n']} distinct recipients took {f(br['ex_egld'])} EGLD off exchanges outside the pipeline (21 / 133,521 last week), pipeline share {br['pipeline_share']:.1f}% against 88.3%. First week with a full 7-day scan and no page-cap terminations, so it is not a lower bound. Largest ex-pipeline recipients are unlabelled wallets at 43,010, 40,000 and 36,505 EGLD. PRE-COMMITTED: holding above ~40 recipients and ~300,000 EGLD next week = a genuine broadening of off-venue accumulation and the strongest bid evidence the model has; falling back under ~25 recipients = this week tracked the rally and the pipeline still dominates the channel."},
 {"item":"COMPOUND RATE - fourth consecutive decline, test unresolvable on a specification defect",
  "weeks_on_list":4,
  "reason":f"{cvc['compound_pct_of_reward_decisions']:.2f}% ({cvc['redelegate_count']} vs {cvc['claim_count']}), lowest of ten. Run #22's branches were 'below 56%' and 'above 59%' and the reading landed in the gap, so the test resolves inconclusive for the second consecutive run of specification defects. RE-REGISTERED with contiguous branches: below 57% next week = the drift is systematic and the compound rate becomes a standing bearish participation indicator; 57% or above = it has stabilised and the four-week decline was a level shift, not a trend."},
 {"item":"THE 229,865 EGLD UNBOND - RETIRED",
  "weeks_on_list":3,
  "reason":f"Unmoved for a second full week: balance {f(ub['balance'],2)} EGLD unchanged, {f(ub['pending_total'])} still unbonded-and-unclaimed inside the delegation contracts, zero outbound transactions and zero function calls. The no-action branch run #22 added fires. The holder is inactive or has lost access; this stops being tracked as forward supply and comes off the list unless it moves."},
 {"item":"UNBONDING QUEUE - first full-set scan resets the series",
  "weeks_on_list":3,
  "reason":f"All {sk['providers_scanned']} contracts paged: {sk['undelegate_callers']} distinct wallets unDelegated {f(sk['undelegated_week'])} EGLD, 2.1x run #22's ten-provider partial. Measured pending {f(sk['pool_total'])}, largest leg 40,888 from a wallet holding 10 EGLD. The residual of {f(sk['residual'])} is again fully absorbed, so no direct-node figure is published for a second run. Treat {f(sk['undelegated_week'])} as point one of a new comparable series - the earlier partial figures are not comparable to it."},
 {"item":"MEX RELATIVE STRENGTH - streak broken, mechanism closed as unexplained",
  "weeks_on_list":6,
  "reason":f"MEX {xx['mex_wow']:+.2f}% vs EGLD {pc:+.2f}% - the first underperformance in six weeks. The mechanism test's two branches both failed: supply {100*(tk['mex_supply']-tk['mex_prev_supply'])/tk['mex_prev_supply']:+.3f}% (needed >1%) and MEX/WEGLD pool depth {xx['mex_pair_depth']['tvl_egld_wow_pct']:+.2f}% in EGLD terms (needed >10%). Per the run #21 rule the model stops generating explanations: the five-week ~9.8pp gap is labelled unexplained flow. GRADUATING off the list."},
 {"item":"STABLECOIN BASE - both wrapped dollars contracted into a rising price",
  "weeks_on_list":1,
  "reason":f"USDC {tk['stable']['USDC-c76f1f']['pct']:+.2f}% ({f(abs(tk['stable']['USDC-c76f1f']['supply']-tk['stable']['USDC-c76f1f']['prev']))} tokens) and USDT {tk['stable']['USDT-f8c08c']['pct']:+.2f}%, ~$77K of on-chain dollars leaving in a +6.4% price week. USDT is negative in two of the last three weeks on a base under 600K. Watch whether this becomes a third consecutive contraction, which would make the dollar base a de-risking instrument in its own right rather than plumbing noise."},
]
json.dump(R,open("/tmp/run23w/part3.json","w"),indent=1,default=str)
print("part3 ok:",len(R["anomalies"]),"anomalies",len(R["watch_list"]),"watch items")
